### ISSUE TITLE
Failing to install EstNLTK on Linux/Anaconda

### ISSUE THREAD

**Issue by Kaljurand** [estnltk/estnltk#104]
Installing v1.6 on Windows 10/Ubuntu/Anaconda3 results in:
```
$ conda install -c estnltk -c conda-forge estnltk
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - anaconda==2018.12=py37_0 -> mkl-service==1.1.2=py37he904b0f_5
  - anaconda==2018.12=py37_0 -> numexpr==2.6.8=py37h9e4a6bb_0
  - estnltk
Use "conda info <package>" to see the dependencies for each package.
```

Installing v1.4 on CentOS/Miniconda2 results in:

```
$ conda install -c estnltk -c conda-forge estnltk=1.4.1
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - conda[version='>=4.5.12']
  - estnltk=1.4.1
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by soras** [comment]
What version of Python are you using? If it is the newest (3.7), you may try to switch to an older one, e.g [Python 3.6](https://conda.io/docs/user-guide/tasks/manage-python.html#installing-a-different-version-of-python) for estnltk v1.6, and then try again. It could be the case that some of estnltk's dependencies are not yet compatible with the newest version of the Python.
As for estnltk v1.4, you can only use Python 3.5, newer versions are not supported.

**Comment by Kaljurand** [comment]
Thanks, using Python v3.6 on Windows 10/Ubuntu did the trick!

```
conda create -n py36 python=3.6 anaconda
conda activate py36
conda install -c estnltk -c conda-forge estnltk
```

However, when importing "estnltk" in Python, I did get an error:

```
...
packages/estnltk/taggers/text_segmentation/clause_segmenter.py", line 46, in __init__
    JavaProcess( 'Osalau.jar', jar_path=JAVARES_PATH, args=args )
...
FileNotFoundError: [Errno 2] No such file or directory: 'java': 'java')
```

This was fixed by:

```
sudo apt-get update
sudo apt-get install default-jre
```

(I'm not sure the documentation is currently mentioning the Java dependency...)

Now things work:

```
(py36) win>~$ python
Python 3.6.6 | packaged by conda-forge | (default, Oct 12 2018, 14:08:43)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import estnltk
>>> estnltk.Text('koeradega').analyse('morphology').morph_analysis
Layer(name=morph_analysis, spans=SL[AS[Span(koeradega, {'clitic': '', 'ending': 'dega', 'form': 'pl kom', 'lemma': 'koer', 'partofspeech': 'S', 'root': 'koer', 'root_tokens': ('koer',)})]])
```

**Comment by rsirel** [comment]
This issue is not closed. Please update readme & documentation documentation. Conda comes now with Python 3.7 default environment, which makes the install fail.
