### ISSUE TITLE
What is the f1 score of the default Ner model ?

### ISSUE THREAD

**Issue by thak123** [estnltk/estnltk#108]
Hi I would like to know the F1 score of the given NER model .

Can I get the link to the original dataset on which it was trained on?

**Comment by AleksTk** [comment]
Hi, F1-score is 87% on this dataset: https://metashare.ut.ee/repository/search/?q=Estonian+NER+corpus. For more details check our paper "Named Entity Recognition in Estonian": https://www.aclweb.org/anthology/W13-2412.pdf

**Comment by swenlaur** [comment]
Kairit Sirts is currently updating the Estonian NER corpus. There are some labelling inconsistencies. If she is done with it will publish the results in metashare again.
