### ISSUE TITLE
ImportError: cannot import name "Tokenizer" from "estnltk"

### ISSUE THREAD

**Issue by km5ar** [estnltk/estnltk#115]
ImportError: cannot import name "Tokenizer" from "estnltk"

python version: 3.9.13 (linux)
also tried on python: 3.7 (MacOs)

any thoughts?

**Comment by soras** [comment]
Hi! estnltk does not have "Tokenizer". Instead, we have TokensTagger, CompoundTokenTagger, SentenceTokenizer. For introduction to estnltk's pipeline, please see [this tutorial](https://github.com/estnltk/estnltk/blob/main/tutorials/basics/introduction_to_nlp_pipeline.ipynb). Specifics about available tokenization taggers can be found in [these tutorials](https://github.com/estnltk/estnltk/tree/main/tutorials/nlp_pipeline/A_text_segmentation).

**Comment by km5ar** [comment]
thank you!

so below page is not the official website? I initially find the "Tokenizer" from here:
https://estnltk.github.io/estnltk/1.1/tutorials/tokenization.html

**Comment by soras** [comment]
> 
> so below page is not the official website? I initially find the "Tokenizer" from here: https://estnltk.github.io/estnltk/1.1/tutorials/tokenization.html

This is a tutorial of an old outdated version (1.1), which is no longer supported. 

Up-to-date tutorials for version 1.7 can be found here: https://github.com/estnltk/estnltk/tree/main/tutorials

**Comment by km5ar** [comment]
Thank you! i'm wondering if there are any way to subset out the following text column?

So I'm trying to use ParagraphTokenizer() on an article, and assume the article have 3 paragraphs, I would like to turn the output into a list of paragraphs. 

Currently I was only able to get the paragraph sentence by using " ".join(text["paragraphs"]["text"][0]), which doesn't seems to be a good idea (see screen shot 2)


![image](https://user-images.githubusercontent.com/54015474/197835462-63c2027e-39e4-4a98-a880-1f15152927e5.png)

![image](https://user-images.githubusercontent.com/54015474/197835808-0b4f2238-17b5-4a4d-af41-227edb899e07.png)

**Comment by soras** [comment]
> Thank you! i'm wondering if there are any way to subset out the following text column?
> 
> So I'm trying to use ParagraphTokenizer() on an article, and assume the article have 3 paragraphs, I would like to turn the output into a list of paragraphs.
> 
> Currently I was only able to get the paragraph sentence by using " ".join(text["paragraphs"]["text"][0]), which doesn't seems to be a good idea (see screen shot 2)

You probably want to use attribute `enclosing_text` to access corresponding raw texts. Following [the example](https://github.com/estnltk/estnltk/blob/main/tutorials/nlp_pipeline/A_text_segmentation/05_paragraphs.ipynb):
```python
>>> # 1st sentence of a paragraph (as raw string)
>>> text['paragraphs'][0][0].enclosing_text
'See on esimene lõik.'
>>> # 2nd sentence of a paragraph (as raw string)
>>> text['paragraphs'][0][1].enclosing_text
'Ja siin teine lause.'
```

```python
>>> # Whole 1st paragraph as raw string
>>> text['paragraphs'][0].enclosing_text
'See on esimene lõik. Ja siin teine lause.'
>>> # Whole 2nd paragraph as raw string
>>> text['paragraphs'][1].enclosing_text
'Siin on teine lõik.'
```

Please read [this tutorial](https://github.com/estnltk/estnltk/blob/main/tutorials/basics/introduction_to_estnltk_api.ipynb) for more details on how to access and iterate spans and annotations in estnltk.
