### ISSUE TITLE
Mac OS: ImportError: cannot import name 'vabamorf' from partially initialized module 'estnltk.vabamorf'

### ISSUE THREAD

**Issue by 35grain** [estnltk/estnltk#116]
Fresh install of estnltk-1.7.1. Even without any other lines of code, the import of estnltk produces following:
`ImportError: cannot import name 'vabamorf' from partially initialized module 'estnltk.vabamorf' (most likely due to a circular import) (/opt/homebrew/lib/python3.10/site-packages/estnltk/vabamorf/__init__.py)`

Any ideas?

**Comment by swenlaur** [comment]
This is a symptom that vabamorf componenti was not compiled for the target platform.
IThe installation works for M1 but through pip
`
conda activate env
pip install estnltk 
` 
Can you specify your hardware profile so that we could address this issue more directly

**Comment by soras** [comment]
Adding to Sven's comment: currently, most of our MacOS binary packages have built for x86_64-based architecture. 
For MacOS with ARM64-based architecture, we only have packages for Python 3.8 and 3.9. 
So, if you're running on ARM64, try switching to 3.8 or 3.9 and installing estnltk via pip.

**Comment by 35grain** [comment]
> Adding to Sven's comment: currently, most of our MacOS binary packages have built for x86_64-based architecture. For MacOS with ARM64-based architecture, we only have packages for Python 3.8 and 3.9. So, if you're running on ARM64, try switching to Python 3.8 or 3.9 and installing estnltk via pip.

The issue appeared for M2 with Python 3.10 indeed, Downgrading to 3.9 solved it. Thanks!

**Comment by adamori** [comment]
I am using python 3.11 on my Mac M1 and it works, but when I create docker image based on `python3.11-slim` I get this `cannot import name 'vabamorf' from partially initialized module 'estnltk.vabamorf'` error.

estnltk version 1.7.2
