### ISSUE TITLE
Add MacOs support.

### ISSUE THREAD

**Issue by tpetmanson** [estnltk/estnltk#19]
Installing Estnltk under MacOs fails.

**Comment by tpetmanson** [comment]
Actually, I got it working at some point during testing when I had access to a MacOs computer. However, I could not test the changes very briefly.

Anyway, In case someone has a Mac computer and has time to fix it, here are some instructions from the top of my head:

1. look into include/fsc/stdfsc.h header file -- this should be where WIN32, UNIX, MAC macros are defined in vabamorf.
2. see how MAC macro gets defined and add/remove necessary headers to get the project compiling.
3. grep source code for #ifdef MAC and get rid of offending functionality that won't compile. For example, in order get vabamorf to build with setup.py build, I had to remove everything related to Windows registry.

Do a full compile, install, test cycle and if it works, then commit the code.

**Comment by tpetmanson** [comment]
Just the message for the duplicate issue:

While installing estnltk on Mac OsX I get the following error:

In file included from include/fsc/fsc.h:6:
include/fsc/stdfsc.h:78:3: error: Only Win32(CE), Unix and Mac are currently supported.
        #error Only Win32(CE), Unix and Mac are currently supported.
         ^
It seems that the installer does not understand that it runs on Mac. Some dependency is missing? Any help?

**Comment by andreskull** [comment]
It is not so easy. I tried setting explicitly in the beginning of stdfsc.h
#define macintosh 
Now it compiles well until:
crfsuite/lib/crf/src/crf1d_model.c:231:5: error: no matching function for call to 'strncpy'
    strncpy(header->magic, FILEMAGIC, 4);

**Comment by tpetmanson** [comment]
`crfsuite/lib/crf/src/crf1d_model.c:231:5: error: no matching function for call to 'strncpy'
strncpy(header->magic, FILEMAGIC, 4);`

This compile error is for a dependency: https://pypi.python.org/pypi/python-crfsuite/0.8.3.
One option is to try to install the dependency separately:
`pip install python-crfsuite==0.8.3`
Second option is that they have some precompiled wheels that dependeing on the OS X version might help you out: https://pypi.python.org/packages/3.4/p/python-crfsuite/python_crfsuite-0.8.3-cp34-cp34m-macosx_10_10_x86_64.whl#md5=0bddccd0997783f494f0949928eade8f

The weird thing is that the compiler error complains that a trivial function `strncpy` is missing, that is defined in `string.h` and should exist on every compiler suite.

**Comment by andreskull** [comment]
It is strange that all dependencies are not correctly compiled from the installer but stand-alone installation goes well (regex and python-crfsuite). After installing those dependencies stand-alone the installation of estnltk (sudo python3 setup.py install) ends successfully.
But now is the issue with _vabamorf
>>> import estnltk
Traceback (most recent call last):
  File "./estnltk/vabamorf/vabamorf.py", line 16, in swig_import_helper
    fp, pathname, description = imp.find_module('_vabamorf', [dirname(__file__)])
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/imp.py", line 244, in find_module
    raise ImportError(_bootstrap._ERR_MSG.format(name), name=name)
ImportError: No module named '_vabamorf'

Installation log does not reveal that something went wrong with _vabamorf

**Comment by tpetmanson** [comment]
Okay, this error is very explicit in that Python cannot load the dynamic linked library for the vabamorf component. It either does not exist or Python cannot find it.

My next step would be cloning the repository (big & slow operation) or downloading the zip https://github.com/estnltk/estnltk/archive/master.zip and then I would try to build directly from this source code:

``python3 setup.py build``

as a result, in ``build`` subdirectory, there will be (should be) two folders, one with ``lib`` and another with ``temp`` prefix. On my Linux box, for Python2.7, there are

```
$ ls build/
lib.linux-x86_64-2.7  temp.linux-x86_64-2.7
```

In this ``lib`` subfolder, the dynamic link library should be somewhere under ``estnltk/vabamorf`` subdirectory. On my machine, it is file ``build/lib.linux-x86_64-2.7/estnltk/vabamorf/_vabamorf.so`` :

```
~/projects/estnltk$ find build/lib.linux-x86_64-2.7/ | grep vabamorf
build/lib.linux-x86_64-2.7/estnltk/vabamorf
build/lib.linux-x86_64-2.7/estnltk/vabamorf/dct
build/lib.linux-x86_64-2.7/estnltk/vabamorf/dct/et.dct
build/lib.linux-x86_64-2.7/estnltk/vabamorf/dct/et3.dct
build/lib.linux-x86_64-2.7/estnltk/vabamorf/__init__.py
build/lib.linux-x86_64-2.7/estnltk/vabamorf/morf.py
build/lib.linux-x86_64-2.7/estnltk/vabamorf/tests
build/lib.linux-x86_64-2.7/estnltk/vabamorf/tests/__init__.py
build/lib.linux-x86_64-2.7/estnltk/vabamorf/tests/test_multi.py
build/lib.linux-x86_64-2.7/estnltk/vabamorf/tests/test_synthesize.py
build/lib.linux-x86_64-2.7/estnltk/vabamorf/tests/test_analyze.py
build/lib.linux-x86_64-2.7/estnltk/vabamorf/tests/test_disambiguate.py
build/lib.linux-x86_64-2.7/estnltk/vabamorf/_vabamorf.so
build/lib.linux-x86_64-2.7/estnltk/vabamorf/vabamorf.i
build/lib.linux-x86_64-2.7/estnltk/tests/test_vabamorf.py
```

However, the library is with ``.pyd`` suffix on Windows, ``.so`` suffix in Linux and it might be something else in OSX. Also, it may have Python version embedded to the file name (not in above example) -- this is quite system and Python version specific. But this is the file that is reported missing.

If the file is generated, then next move would be copying it to working directory and then I would to execute this line for test:
```
python3 -c "import estnltk; print( estnltk.Text('Tere estnltk').lemmas )"
```

However, if the file is not generated, I guess I would need to see full build log and possibly we might need to modify settings in ``setup.py`` file.

If you get a chance, then you could try above and compile the library from source?
If it does not work the way expected, then could you also post the build log? Maybe we can dig up something from there. Unfortunately I cannot try any of this myself as I don't have any OS X capable machine to test it with.

If all this works, then there must be some problem with how ``pip`` or Python is configured on the system. Otherwise, there maybe something wrong with the compiler settings.
By the way, what C++ compiler/version you have on your system?

**Comment by andreskull** [comment]
I found _vabamorf.so 
$ find . | grep _vabamorf
./build/lib.macosx-10.6-x86_64-3.3/estnltk/tests/test_vabamorf.py
./build/lib.macosx-10.6-x86_64-3.3/estnltk/vabamorf/_vabamorf.so

I executed the following successfully in the folder with _vabamorf.so: 
Executing python3 -c "import estnltk; print( estnltk.Text('Tere estnltk').lemmas )"
[nltk_data] Downloading package punkt to
[nltk_data]     /Users/andreskull/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
['tere', 'estnltk']

My C++ compiler version:
$ c++ -v
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin14.5.0
Thread model: posix

**Comment by tpetmanson** [comment]
Mac OS X support now works, hopefully! Compile & install worked on Arvi's MacBook Air. The OS version is Os X Yosemite 10.10.5 . Changes are in devel branch, please confirm!

**Comment by arvitavast** [comment]
If NLTK gives you UTF-8 invalid error, then add this to your bash profile
    
    export LC_ALL=en_US.UTF-8  
    export LANG=en_US.UTF-8

**Comment by andreskull** [comment]
I get compilation error:
In file included from include/fsc/fsstring.h:16:
include/fsc/fsthread.h:321:8: error: unknown type name 'FSTHREADID'
inline FSTHREADID FSGetCurrentThreadID(){

**Comment by kristiank** [comment]
Instead of ```en_US.UTF-8``` one might prefer a more local version of utf8: ```et_EE.UTF-8```.

**Comment by tpetmanson** [comment]
I guess that the problem now is that Andres uses LLVM while Arvi used GCC.
We had some time at EKT conference to hack the Mac OS X support, so we changed stdfsc.h to look like this:

    #if defined (WIN32CE)
        ... irrelevant right now ...
    #elif defined (WIN32)
        ... irrelevant right now ...
    #else
    //#elif defined (UNIX)
        #pragma message("UNIX block")
        #include <stdio.h>
        #include <stdlib.h>
        #include <stdarg.h>
        #include <string.h>
        #include <ctype.h>
        #include <wchar.h>
        #include <math.h>
        #include <pthread.h>
        #include <signal.h>
        #include <dlfcn.h>
        #include <sys/time.h>
    //#elif defined (MAC)
    //  #pragma message("MAC block")
    //  #include <stdio.h>
    //  #include <stdlib.h>
    //  #include <stdarg.h>
    //  #include <string.h>
    //  #include <ctype.h>
    //  #include <wchar.h>
    //  #include <dlfcn.h>
    //#else
    //  #error Only Win32(CE), Unix and Mac are currently supported.
    #endif

In other words, UNIX headers worked fine for Mac with GCC.
However, as Andres actually got it compiling by putting

#define macintosh

in the beginning, I guess LLVM works with headers in MAC block

I would try this next:

    #if defined (WIN32CE)
        ... irrelevant right now ...
    #elif defined (WIN32)
        ... irrelevant right now ...
    #elif defined(__clang__) // maybe it should be defined(__clang__) && defined(macintosh) ?
        #include <stdio.h>
        #include <stdlib.h>
        #include <stdarg.h>
        #include <string.h>
        #include <ctype.h>
        #include <wchar.h>
        #include <dlfcn.h>
    #else // by default, assume it is GCC or something compatible
        #include <stdio.h>
        #include <stdlib.h>
        #include <stdarg.h>
        #include <string.h>
        #include <ctype.h>
        #include <wchar.h>
        #include <math.h>
        #include <pthread.h>
        #include <signal.h>
        #include <dlfcn.h>
        #include <sys/time.h>
    #endif

But again, I cannot test it on a macbook myself.

NB! We used Python3.4

**Comment by andreskull** [comment]
tried with 
#elif defined(__clang__) 
no effect

tried with defined(__clang__) && defined(macintosh) also well, no effect,

**Comment by ikiissel** [comment]
Andres, this might be helpful
https://github.com/Filosoft/vabamorf/issues/23

**Comment by tpetmanson** [comment]
Hello again, OSX users. Yesterday I had the change to hack another OSX machine and we got estnltk to compile. Basically, we added just one line that did the trick:

    #else
    //#elif defined (UNIX)
        #pragma message("UNIX block")
        #define UNIX                    // <- we added this line
        #include <stdio.h>
        #include <stdlib.h>
        #include <stdarg.h>
        #include <string.h>
        #include <ctype.h>
        #include <wchar.h>
        #include <math.h>
        #include <pthread.h>
        #include <signal.h>
        #include <dlfcn.h>
        #include <sys/time.h>
    //#elif defined (MAC)
    //  #pragma message("MAC block")
    //  #include <stdio.h>
    //  #include <stdlib.h>
    //  #include <stdarg.h>
    //  #include <string.h>
    //  #include <ctype.h>
    //  #include <wchar.h>
    //  #include <dlfcn.h>
    //#else
    //  #error Only Win32(CE), Unix and Mac are currently supported.
    #endif

Also pushed the change into a separate branch: https://github.com/estnltk/estnltk/tree/osxtest . Please confirm the fix.

**Comment by andreskull** [comment]
It works in my Mac now!

**Comment by tpetmanson** [comment]
This is good news!

**Comment by NetBUG** [comment]
@tpetmanson Also confirm the fix in `stdfsc.h`, I think you can merge it to master.
