### ISSUE TITLE
Fix some problems with word tokenizer

### ISSUE THREAD

**Issue by tpetmanson** [estnltk/estnltk#25]
järgarvud, 1., 2. ,3.
sidekriipsudega liitsõnad
- Prantsuse-Frank, D-vitamiin
- esma-, liblik- ja põimõielised
- numbrid 3,14 ; 3.14 ; 3/4

**Comment by soras** [comment]
Lisaks siia, et osad ajaväljendid jäävad samuti eraldamata või eraldatakse katkiselt, kuna NLTK WordPunctTokenizer'i sõnestamisloogika ei sobi hästi ajaväljendite tuvastajale. Sellised ajaväljendid on nt ('TIMEX examples' tabelist):
* VI sajandist e. m. a
* 2004. aastal
* 2009. aasta alguses
* 2009. aasta esimesel poolel
* 12-15 märts 2009
* 2004. aasta suvel
* täna, 100 aastat tagasi

Kui kasutada nende ajaväljendite eeltöötluses WordPunctTokenizer'i asemel WhitespaceTokenizer'it, siis kõik toimib. Võib-olla tulekski teha nii, et ajaväljendite tuvastamiseks kasutataks alati vaikimisi hoopis WhitespaceTokenizer'it?

**Comment by kristiank** [comment]
Kas te ei vöiks teha ```WordPunctTokenizer``` klassi eesti keele jaoks?
Mõned lihtsad üksustamisreeglid numbrite ja punktidega leidub [siit](https://github.com/kristiank/Lausestaja). Mind huvitaks väga, kui tekkiks *üks* koht, kus eesti üksustamise reegleid, olgu sõnestamise, lausestamise või muu üksustamise reegleid saaks iteratiivselt aina paremaks teha ja oleks kõigile lihtsalt ja dokumenteeritult kättesaadav. Seni on umbes 55 aastat olnud ainult eraldi projektide jaoks eraldi reeglikogusid töörühmade endi rüpes.

**Comment by tpetmanson** [comment]
Mina pooldan seda mõtet, et estnltk oleks koht, kuhu kogu eesti keele tükeldamise know-how kokku võiks joosta. Aga mulle oleks vaja natuke infot ja abi, et see asi käima panna.

1. Lausestajal/sõnestajal võiks olla mingi benchmark andmestik, mille järgi neid kontrollida ja parandada. Selleks vist võiks sobida morfoloogiliselt ühestatud korpus? Või ehk ka midagi kus oleks mustemat sisendit? Ainus asi, et morf-ühestatud korpusel võiks olla ka olemas tükeldamata algtekstid või siis tuleks need kuidagi rekonstrueerida.

2. Samuti võiks kokku koguda kõik vabavaralised juba olemasolevad tarkvaratükid ning neid siin viidata. Heameelega taaskasutaks neid sellisel juhul Estnltk-s kui võimalik.  Aga esitan siis ka palve laiemale kasutajaskonnale: palun saatke lausestamist/sõnestamist tegevaid vabavaralisi programme/koodi, mis võiks teie arvates estnltk-s sees olla. Ideaalis võiks need olla Pythonis.

Lisan siia esimesena Kristjani programmi.

https://github.com/kristiank/Lausestaja - kolmetasandiline keela-luba-keela reeglite
kogum, mida on lihtne ise muuta ja täiendada. Seetõttu on lihtne ka uusi
mudeleid luua uutele keeltele. Praegu on üks üldine eesti keele jaoks, ja üks
spetsiifiline võru keele jaoks.

**Comment by kristiank** [comment]
1. Selline n.ö kuldstandardi andmestiku tekitamise juures võiks abi ja nõu küsida (tagurpidi kirjutatud) pelaaK J-H
2. Keeleleegi vikis on püütud koostada loendeid eesti keeleressursside üle. Ressursside loend [siin](http://viki.keeleleek.ee/wiki/Eesti_keele_ressursside_loend) on üpris pikk. Tarkvara pole suutud üldse samal mahul loetleda, nagu näha [siit](http://viki.keeleleek.ee/wiki/Eesti_keele_tarkvara_loend). Kas oleks mõttekas suunata kogumisjõud sinna?

**Comment by tpetmanson** [comment]
implementeeritud 1.3-s ``EstWordTokenizer`` klassina
