### ISSUE TITLE
Text.named_entities outputs words with wrong capital cases

### ISSUE THREAD

**Issue by tpetmanson** [estnltk/estnltk#30]
Bug report:

Tere! Võtsin nüüd uuema versiooni kasutusele. Selline küsimus, et kas on mingi põhjus miks leitud nimede ( NER) teine sõna on väikese tähega. Näiteks on tekst selline:

_Ennelõunal peetud meeste võistlusel jõudsid pingelistes matsides nelja parema hulka Haapsalu vehklemisklubi En Garde esindaja Sten Priinits, klubi Le Glaive Haapsalu taustaga vehklejad Nikolai Novosjolov ja Marno Allika ning Jüri Salm Tallinna Mõõgast._

Siit leitakse järgmised asjad (muuhulgas):

```
('Marno allikas', 'PER')
('Jüri Salm', 'PER')
```

Esimene nimi leitakse veidral kujul, teine õigel kujul. Sama moodi muudetakse väikese tähega algavaks ka mõnede organisatsioonide teine või kolma sõna.

**Comment by tpetmanson** [comment]
See on hea tähelepanek ja ma arvan, et see läheb bugina kirja.
Põhjus on selles, et nimeolemite kiht on kirjeldatud peamiselt ainult alg- ja lõppindeksite abil:

    >>> text['named_entities']
    [{'label': 'LOC', 'end': 92, 'start': 84}, {'label': 'ORG', 'end': 116, 'start': 108}, 
    {'label': 'PER', 'end': 139, 'start': 126}, {'label': 'PER', 'end': 156, 'start': 147}, 
    {'label': 'LOC', 'end': 165, 'start': 157}, {'label': 'PER', 'end': 203, 'start': 185}, 
    {'label': 'PER', 'end': 219, 'start': 207}, {'label': 'PER', 'end': 234, 'start': 225}, 
    {'label': 'LOC', 'end': 251, 'start': 235}]

ning .named_entities kasutamisel proovib estnltk anda nimeolemid algvormis ja kasutab selleks sõnade lemmasid, mis vastava nimeolemi sisse mahuvad.
Lemmad aga tulevad otse morfoanalüsaatorist:

    >>> text.lemmas
    ['ennelõuna', 'peetud|peetuma|pidama', 'mees', 'võistlus', 'jõudma', 
    'pingeline', 'mats', 'neli', 'parem', 'hulka', 'Haapsalu', 'vehklemisklubi',
     'En', 'Garde', 'esindaja', 'Sten',  'Priinits', ',', 'klubi', 'Le', 'Glaive',
     'Haapsalu', 'taust', 'vehkleja', 'Nikolai', 'Novosjolov', 'ja', 
    'Marno', 'allikas', 'ning', 'Jüri', 'Salm', 'Tallinn', 'mõõk', '.']

siin on näha, et "allikas" on samuti väikese tähega (morfoanalüsaator ei pea seda nime osaks). Probleem on selles, et estnltk ei kontrolli, kas algtekstis olev sõna on suure või väikese tähega, vaid kasutab otse morfoanalüsaatori väljundit nimeolemite algvormi kokkupanemiseks.

Pakun momendil välja kolm lahendust:

* Esimene on kasutada:

     >>> text.named_entity_texts
    ['Haapsalu', 'En Garde', 'Sten Priinits', 'Le Glaive', 'Haapsalu',
    'Nikolai Novosjolov', 'Marno Allika', 'Jüri Salm',
     'Tallinna Mõõgast']

see annab nimeolemid välja täpselt sellisel kujul nagu nad algses tekstis on. Aga probleem on, et nimeolemid on käänatud ja neid ei saa sellisel kujul kasutada näiteks indekseerimiseks/grupeerimiseks/kokkulugemiseks vm mis eeldab, et nad on algvormis.

* Teine variant on tulemused ise teisendada kõik uppercase/lowercase. Tulemusena on eri käänetes olevad nimeolemid alati algvormis, aga pole alati teada, kas sõnad on suure või väikese tähega.

* Kolmas variant on parandada estnltk-s text klassi named_entities property. Parandamiseks tuleb sinna lisada see, et lemma algustäht muudetakse suureks/väikeseks algse sõna järgi. Tegelikult lihtne ülesanne, aga nõuab estnltk otse lähtekoodist ehitamist ja parandus ametlikku versiooni jõuab arvestatava hilinemisega (ca pool aastat).

**Comment by tammelv** [comment]
See teema küll otseselt suure/väikse algustähe alla ei kuulu, aga kuna seotud NERi ja veidi esimese variandiga siis lisan siia. 
On tekst: "Postimehe juhatuse esimehe ja peatoimetajana jätkab Merit Kopli" Kui see läbi NERi lasta, siis saab isiku nimeks "Meri Kopli". 
Samas, kui on tekst "Postimees jätkab Merit Kopliga" saan tulemuseks "Meri koppel"
Tundub, nagu käänatakse eesnimi samuti algvormi. 

Kas grammatikas ei olnud nii, et ainult viimane sõna käändub? Sellisel juhul saaks jätta kõikide sõnade algvormi välja arvatud viimase ning viimane sõna siis asendada algvormiga.

**Comment by swenlaur** [comment]
Viga sellisel kujul on refaktoreerimiste käigus kadunud. Ebakindlus NER määramise suhtes on säilinud (madal saagis). Lahenduseks on uue treeningandmestiku loomine ja uue mudeli treenimine.
