### ISSUE TITLE
EstNLTK eager/explicit evaluation

### ISSUE THREAD

**Issue by tpetmanson** [estnltk/estnltk#31]
Add new parameter to Text class that can be used to turn off computing new features if they do not exist.

```
text = Text('tere estnltk', enable_tagging=False)
```

For example, lemma extraction works currently as following:

```
@cached_property
def lemmas(self):
    if not self.is_tagged(ANALYSIS):
        self.tag_analysis()
    return self.get_analysis_element(LEMMA)
```

As a result, the code should be changed to

```
@cached_property
def lemmas(self):
    if not self.is_tagged(ANALYSIS) and self.enable_tagging:
        self.tag_analysis()
    return self.get_analysis_element(LEMMA)
```

**Comment by swenlaur** [comment]
Talked with Uku about this issue. He needs this issue urgently. Object level decisions about eager/explicit evaluation are good. However, could we  also can we have global default for the `enable_tagging` flag like `ESTNLTK_ENABLE_TAGGING_DEFAULT` that could be used to control the default behaviour.

**Comment by swenlaur** [comment]
This issue has been revolved by defining BaseText class which gives explicit control what layers are created and how taggers are called to the programmers hand. The standard class Text does on demand behind the scenes computations.
