### ISSUE TITLE
Rename partofspeech in analysis dictionary

### ISSUE THREAD

**Issue by tpetmanson** [estnltk/estnltk#33]
It should be either
- `part_of_speech`, so it is consistent with underscore-style naming with multiple words as the rest of the names.
- `pos` or `postag`, which is just shorter.

The change requires modifiyng a variable in `names.py` module. The only problem is that this change _will_ break user code.

**Comment by urdvr** [comment]
Closing as stale. 

And I'd rather avoid breaking user code for a stylistic change.
