### ISSUE TITLE
Upgrade Elastic data importer and bulk insert methods

### ISSUE THREAD

**Issue by tpetmanson** [estnltk/estnltk#36]
Current implementation is a little bit hacky, it would be better to replace them with built-in methods in elasticsearch.helpers package.

References:
http://elasticsearch-py.readthedocs.org/en/master/helpers.html
http://stackoverflow.com/questions/20288770/how-to-use-bulk-api-to-store-the-keywords-in-es-by-using-python

**Comment by swenlaur** [comment]
Exporter to elasticsearch is now considered as legacy. Use postgre or SQLite instead for serialisation.
