### ISSUE TITLE
What versions of elasticsearch should estnltk support? 

### ISSUE THREAD

**Issue by urdvr** [estnltk/estnltk#37]
Elastic.co has released Elasticsearch 2.0 (ES2) with breaking changes in the query syntax.

What versions of Elasticsearch should estnltk support? Is the database interface used outside of STACC?

Some thoughts in no particular order:

1. New users of elasticsearch are likely to download ES2 as it is the one prominently displayed on the elastic.co website.
2. The default downloads of tools (kibana, marvel, shield etc.) from elastic.co do not support ES versions below 2.
3. Previous versions of ES are going to stick around for a while (Amazon Elasticsearch Service is currently on ES1.5.2.)
4. Documentation for ES2 is average or below average. I'm generally not happy about the documentation of ES1.7 as well, but it has had time to have books and third-party manuals written about it.

The options as I see them are:

1. Support ES1.7 and not ES2
2. Support both ES1.7 and ES2
3. Support ES2 and not ES1.7

I would prefer not to do option 2 as time and devresources are limited. Option 3 appeals to me because it is a transition that would have to be made sooner or later and making it now is least likely to break user code. 

Discuss.

**Comment by tpetmanson** [comment]
I would also vote for option "(3) Support ES2 and not ES1.7". AFAIK nobody outside STACC depend on the library. Also, current elastic wrapper codebase is quite minimal, so we should move as soon as possible, before adding new stuff

**Comment by urdvr** [comment]
estnltk moves with the times, supports ES2+
