### ISSUE TITLE
inconsistent use of tabs and spaces in indentation: lit_pos_synidx_parser.py

### ISSUE THREAD

**Issue by urdvr** [estnltk/estnltk#43]
``` bash
$ pip install estnltk
```

Estnltk install succeeds, but logs the following:
`Sorry: TabError: inconsistent use of tabs and spaces in indentation (lit_pos_synidx_parser.py, line 39)`

``` bash
$ python --version
Python 3.4.3
```

**Comment by swenlaur** [comment]
These files are not part of EstNLTK any more.
