### ISSUE TITLE
Verb chain detection fails on previously analyzed text.

### ISSUE THREAD

**Issue by urdvr** [estnltk/estnltk#46]
``` python
import estnltk

t = { "text": "See on väga sügavamõtteline teema ja vastuseid igasuguseid , kui ma olen kindel et THE TRUTH IS OUT SOMEWHERE !!", "words": [ { "start": 0, "text": "See", "end": 3, "analysis": [ { "root_tokens": [ "see" ], "ending": "0", "form": "sg n", "partofspeech": "P", "lemma": "see", "clitic": "", "root": "see" } ] }, { "start": 4, "text": "on", "end": 6, "analysis": [ { "root_tokens": [ "ole" ], "ending": "0", "form": "b", "partofspeech": "V", "lemma": "olema", "clitic": "", "root": "ole" }, { "root_tokens": [ "ole" ], "ending": "0", "form": "vad", "partofspeech": "V", "lemma": "olema", "clitic": "", "root": "ole" } ] }, { "start": 7, "text": "väga", "end": 11, "analysis": [ { "root_tokens": [ "väga" ], "ending": "0", "form": "", "partofspeech": "D", "lemma": "väga", "clitic": "", "root": "väga" } ] }, { "start": 12, "text": "sügavamõtteline", "end": 27, "analysis": [ { "root_tokens": [ "sügava", "mõtteline" ], "ending": "0", "form": "sg n", "partofspeech": "A", "lemma": "sügavamõtteline", "clitic": "", "root": "sügava_mõtteline" } ] }, { "start": 28, "text": "teema", "end": 33, "analysis": [ { "root_tokens": [ "teema" ], "ending": "0", "form": "sg n", "partofspeech": "S", "lemma": "teema", "clitic": "", "root": "teema" } ] }, { "start": 34, "text": "ja", "end": 36, "analysis": [ { "root_tokens": [ "ja" ], "ending": "0", "form": "", "partofspeech": "J", "lemma": "ja", "clitic": "", "root": "ja" } ] }, { "start": 37, "text": "vastuseid", "end": 46, "analysis": [ { "root_tokens": [ "vastus" ], "ending": "id", "form": "pl p", "partofspeech": "S", "lemma": "vastus", "clitic": "", "root": "vastus" } ] }, { "start": 47, "text": "igasuguseid", "end": 58, "analysis": [ { "root_tokens": [ "iga", "sugune" ], "ending": "id", "form": "pl p", "partofspeech": "P", "lemma": "igasugune", "clitic": "", "root": "iga_sugune" } ] }, { "start": 59, "text": ",", "end": 60, "analysis": [ { "root_tokens": [ "," ], "ending": "", "form": "", "partofspeech": "Z", "lemma": ",", "clitic": "", "root": "," } ] }, { "start": 61, "text": "kui", "end": 64, "analysis": [ { "root_tokens": [ "kui" ], "ending": "0", "form": "", "partofspeech": "D", "lemma": "kui", "clitic": "", "root": "kui" }, { "root_tokens": [ "kui" ], "ending": "0", "form": "", "partofspeech": "J", "lemma": "kui", "clitic": "", "root": "kui" } ] }, { "start": 65, "text": "ma", "end": 67, "analysis": [ { "root_tokens": [ "mina" ], "ending": "0", "form": "sg n", "partofspeech": "P", "lemma": "mina", "clitic": "", "root": "mina" } ] }, { "start": 68, "text": "olen", "end": 72, "analysis": [ { "root_tokens": [ "ole" ], "ending": "n", "form": "n", "partofspeech": "V", "lemma": "olema", "clitic": "", "root": "ole" } ] }, { "start": 73, "text": "kindel", "end": 79, "analysis": [ { "root_tokens": [ "kindel" ], "ending": "0", "form": "sg n", "partofspeech": "A", "lemma": "kindel", "clitic": "", "root": "kindel" } ] }, { "start": 80, "text": "et", "end": 82, "analysis": [ { "root_tokens": [ "et" ], "ending": "0", "form": "", "partofspeech": "J", "lemma": "et", "clitic": "", "root": "et" } ] }, { "start": 83, "text": "THE", "end": 86, "analysis": [ { "root_tokens": [ "THE" ], "ending": "0", "form": "?", "partofspeech": "Y", "lemma": "THE", "clitic": "", "root": "THE" } ] }, { "start": 87, "text": "TRUTH", "end": 92, "analysis": [ { "root_tokens": [ "TRUTH" ], "ending": "0", "form": "?", "partofspeech": "Y", "lemma": "TRUTH", "clitic": "", "root": "TRUTH" } ] }, { "start": 93, "text": "IS", "end": 95, "analysis": [ { "root_tokens": [ "IS" ], "ending": "0", "form": "?", "partofspeech": "Y", "lemma": "IS", "clitic": "", "root": "IS" } ] }, { "start": 96, "text": "OUT", "end": 99, "analysis": [ { "root_tokens": [ "OUT" ], "ending": "0", "form": "?", "partofspeech": "Y", "lemma": "OUT", "clitic": "", "root": "OUT" } ] }, { "start": 100, "text": "SOMEWHERE", "end": 109, "analysis": [ { "root_tokens": [ "Somewhere" ], "ending": "0", "form": "sg n", "partofspeech": "H", "lemma": "Somewhere", "clitic": "", "root": "Somewhere" } ] }, { "start": 110, "text": "!!", "end": 112, "analysis": [ { "root_tokens": [ "!!" ], "ending": "", "form": "", "partofspeech": "Z", "lemma": "!!", "clitic": "", "root": "!!" } ] } ], }


estnltk.Text(t).verb_chains()
```

raises 

```
  File "data.py", line 7, in <module>
    estnltk.Text(t).verb_chains()
  File "/home/uku/anaconda3/lib/python3.5/site-packages/cached_property.py", line 26, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/uku/anaconda3/lib/python3.5/site-packages/estnltk/text.py", line 881, in verb_chains
    self.tag_verb_chains()
  File "/home/uku/anaconda3/lib/python3.5/site-packages/estnltk/text.py", line 860, in tag_verb_chains
    self.tag_clauses()
  File "/home/uku/anaconda3/lib/python3.5/site-packages/estnltk/text.py", line 833, in tag_clauses
    clauses.extend(from_sentence(sentence))
  File "/home/uku/anaconda3/lib/python3.5/site-packages/estnltk/text.py", line 818, in from_sentence
    start = words[0][START]
```

Problem seems to be in different analyses of `!!` and whether the text is one sentence or two.

**Comment by soras** [comment]
Viga ei teki otseselt verbiahelate tuvastajas, vaid ühes eeltöötluse sammus: teksti jagamisel lauseteks.  Probleem, jah, selles, et lauselõpulise ``!!`` keskele tõmmatakse ekslikult lausepiir, tekib kaks lauset ning seetõttu ka vastuolu sisendiga, kus on vaid üks lause.
Paistab, et see sisendtekst on analüüsitud kuidagi teisiti kui analüüsib estnltk praegune versioon (mõne varasema esnltk versiooniga või mingi teistsuguse lausestajaga?), vastasel juhul viga ei tohiks tekkida.

*Lahendus 1.* Analüüsida kogu tekst uuesti::

    from estnltk import Text
    t = { "text": "See on väga sügavamõtteline teema ja vastuseid igasuguseid , kui ma olen kindel et THE TRUTH IS OUT SOMEWHERE !!", "words": [ { "start": 0, "text": "See", "end": 3, "analysis": [ { "root_tokens": [ "see" ], "ending": "0", "form": "sg n", "partofspeech": "P", "lemma": "see", "clitic": "", "root": "see" } ] }, { "start": 4, "text": "on", "end": 6, "analysis": [ { "root_tokens": [ "ole" ], "ending": "0", "form": "b", "partofspeech": "V", "lemma": "olema", "clitic": "", "root": "ole" }, { "root_tokens": [ "ole" ], "ending": "0", "form": "vad", "partofspeech": "V", "lemma": "olema", "clitic": "", "root": "ole" } ] }, { "start": 7, "text": "väga", "end": 11, "analysis": [ { "root_tokens": [ "väga" ], "ending": "0", "form": "", "partofspeech": "D", "lemma": "väga", "clitic": "", "root": "väga" } ] }, { "start": 12, "text": "sügavamõtteline", "end": 27, "analysis": [ { "root_tokens": [ "sügava", "mõtteline" ], "ending": "0", "form": "sg n", "partofspeech": "A", "lemma": "sügavamõtteline", "clitic": "", "root": "sügava_mõtteline" } ] }, { "start": 28, "text": "teema", "end": 33, "analysis": [ { "root_tokens": [ "teema" ], "ending": "0", "form": "sg n", "partofspeech": "S", "lemma": "teema", "clitic": "", "root": "teema" } ] }, { "start": 34, "text": "ja", "end": 36, "analysis": [ { "root_tokens": [ "ja" ], "ending": "0", "form": "", "partofspeech": "J", "lemma": "ja", "clitic": "", "root": "ja" } ] }, { "start": 37, "text": "vastuseid", "end": 46, "analysis": [ { "root_tokens": [ "vastus" ], "ending": "id", "form": "pl p", "partofspeech": "S", "lemma": "vastus", "clitic": "", "root": "vastus" } ] }, { "start": 47, "text": "igasuguseid", "end": 58, "analysis": [ { "root_tokens": [ "iga", "sugune" ], "ending": "id", "form": "pl p", "partofspeech": "P", "lemma": "igasugune", "clitic": "", "root": "iga_sugune" } ] }, { "start": 59, "text": ",", "end": 60, "analysis": [ { "root_tokens": [ "," ], "ending": "", "form": "", "partofspeech": "Z", "lemma": ",", "clitic": "", "root": "," } ] }, { "start": 61, "text": "kui", "end": 64, "analysis": [ { "root_tokens": [ "kui" ], "ending": "0", "form": "", "partofspeech": "D", "lemma": "kui", "clitic": "", "root": "kui" }, { "root_tokens": [ "kui" ], "ending": "0", "form": "", "partofspeech": "J", "lemma": "kui", "clitic": "", "root": "kui" } ] }, { "start": 65, "text": "ma", "end": 67, "analysis": [ { "root_tokens": [ "mina" ], "ending": "0", "form": "sg n", "partofspeech": "P", "lemma": "mina", "clitic": "", "root": "mina" } ] }, { "start": 68, "text": "olen", "end": 72, "analysis": [ { "root_tokens": [ "ole" ], "ending": "n", "form": "n", "partofspeech": "V", "lemma": "olema", "clitic": "", "root": "ole" } ] }, { "start": 73, "text": "kindel", "end": 79, "analysis": [ { "root_tokens": [ "kindel" ], "ending": "0", "form": "sg n", "partofspeech": "A", "lemma": "kindel", "clitic": "", "root": "kindel" } ] }, { "start": 80, "text": "et", "end": 82, "analysis": [ { "root_tokens": [ "et" ], "ending": "0", "form": "", "partofspeech": "J", "lemma": "et", "clitic": "", "root": "et" } ] }, { "start": 83, "text": "THE", "end": 86, "analysis": [ { "root_tokens": [ "THE" ], "ending": "0", "form": "?", "partofspeech": "Y", "lemma": "THE", "clitic": "", "root": "THE" } ] }, { "start": 87, "text": "TRUTH", "end": 92, "analysis": [ { "root_tokens": [ "TRUTH" ], "ending": "0", "form": "?", "partofspeech": "Y", "lemma": "TRUTH", "clitic": "", "root": "TRUTH" } ] }, { "start": 93, "text": "IS", "end": 95, "analysis": [ { "root_tokens": [ "IS" ], "ending": "0", "form": "?", "partofspeech": "Y", "lemma": "IS", "clitic": "", "root": "IS" } ] }, { "start": 96, "text": "OUT", "end": 99, "analysis": [ { "root_tokens": [ "OUT" ], "ending": "0", "form": "?", "partofspeech": "Y", "lemma": "OUT", "clitic": "", "root": "OUT" } ] }, { "start": 100, "text": "SOMEWHERE", "end": 109, "analysis": [ { "root_tokens": [ "Somewhere" ], "ending": "0", "form": "sg n", "partofspeech": "H", "lemma": "Somewhere", "clitic": "", "root": "Somewhere" } ] }, { "start": 110, "text": "!!", "end": 112, "analysis": [ { "root_tokens": [ "!!" ], "ending": "", "form": "", "partofspeech": "Z", "lemma": "!!", "clitic": "", "root": "!!" } ] } ], }

    Text(t['text']).verb_chains

Või kui on suurem korpus, analüüsida uuesti vaid ``!!`` sisaldavad laused/tekstid, kuna viga paistab otseselt olevat seotud vaid selle märgijadaga.

*Lahendus 2.* Osa probleemist on see, et sisendis puuduvad lausepiiride analüüsid. Kui lausepiiride analüüsid oleks olemas, siis ei hakatakski teksti uuesti lauseteks jagama ja konflikti ei tekiks. Ehk siis variant oleks lausepiirid ise tekitada, nt võtta ``"words"`` esimese elemendi alguspositsioon lausealguseks ning ``"words"`` viimase elemendi lõpupositsioon lauselõpuks::

    from estnltk import Text
    t = { "text": "See on väga sügavamõtteline teema ja vastuseid igasuguseid , kui ma olen kindel et THE TRUTH IS OUT SOMEWHERE !!", "words": [ { "start": 0, "text": "See", "end": 3, "analysis": [ { "root_tokens": [ "see" ], "ending": "0", "form": "sg n", "partofspeech": "P", "lemma": "see", "clitic": "", "root": "see" } ] }, { "start": 4, "text": "on", "end": 6, "analysis": [ { "root_tokens": [ "ole" ], "ending": "0", "form": "b", "partofspeech": "V", "lemma": "olema", "clitic": "", "root": "ole" }, { "root_tokens": [ "ole" ], "ending": "0", "form": "vad", "partofspeech": "V", "lemma": "olema", "clitic": "", "root": "ole" } ] }, { "start": 7, "text": "väga", "end": 11, "analysis": [ { "root_tokens": [ "väga" ], "ending": "0", "form": "", "partofspeech": "D", "lemma": "väga", "clitic": "", "root": "väga" } ] }, { "start": 12, "text": "sügavamõtteline", "end": 27, "analysis": [ { "root_tokens": [ "sügava", "mõtteline" ], "ending": "0", "form": "sg n", "partofspeech": "A", "lemma": "sügavamõtteline", "clitic": "", "root": "sügava_mõtteline" } ] }, { "start": 28, "text": "teema", "end": 33, "analysis": [ { "root_tokens": [ "teema" ], "ending": "0", "form": "sg n", "partofspeech": "S", "lemma": "teema", "clitic": "", "root": "teema" } ] }, { "start": 34, "text": "ja", "end": 36, "analysis": [ { "root_tokens": [ "ja" ], "ending": "0", "form": "", "partofspeech": "J", "lemma": "ja", "clitic": "", "root": "ja" } ] }, { "start": 37, "text": "vastuseid", "end": 46, "analysis": [ { "root_tokens": [ "vastus" ], "ending": "id", "form": "pl p", "partofspeech": "S", "lemma": "vastus", "clitic": "", "root": "vastus" } ] }, { "start": 47, "text": "igasuguseid", "end": 58, "analysis": [ { "root_tokens": [ "iga", "sugune" ], "ending": "id", "form": "pl p", "partofspeech": "P", "lemma": "igasugune", "clitic": "", "root": "iga_sugune" } ] }, { "start": 59, "text": ",", "end": 60, "analysis": [ { "root_tokens": [ "," ], "ending": "", "form": "", "partofspeech": "Z", "lemma": ",", "clitic": "", "root": "," } ] }, { "start": 61, "text": "kui", "end": 64, "analysis": [ { "root_tokens": [ "kui" ], "ending": "0", "form": "", "partofspeech": "D", "lemma": "kui", "clitic": "", "root": "kui" }, { "root_tokens": [ "kui" ], "ending": "0", "form": "", "partofspeech": "J", "lemma": "kui", "clitic": "", "root": "kui" } ] }, { "start": 65, "text": "ma", "end": 67, "analysis": [ { "root_tokens": [ "mina" ], "ending": "0", "form": "sg n", "partofspeech": "P", "lemma": "mina", "clitic": "", "root": "mina" } ] }, { "start": 68, "text": "olen", "end": 72, "analysis": [ { "root_tokens": [ "ole" ], "ending": "n", "form": "n", "partofspeech": "V", "lemma": "olema", "clitic": "", "root": "ole" } ] }, { "start": 73, "text": "kindel", "end": 79, "analysis": [ { "root_tokens": [ "kindel" ], "ending": "0", "form": "sg n", "partofspeech": "A", "lemma": "kindel", "clitic": "", "root": "kindel" } ] }, { "start": 80, "text": "et", "end": 82, "analysis": [ { "root_tokens": [ "et" ], "ending": "0", "form": "", "partofspeech": "J", "lemma": "et", "clitic": "", "root": "et" } ] }, { "start": 83, "text": "THE", "end": 86, "analysis": [ { "root_tokens": [ "THE" ], "ending": "0", "form": "?", "partofspeech": "Y", "lemma": "THE", "clitic": "", "root": "THE" } ] }, { "start": 87, "text": "TRUTH", "end": 92, "analysis": [ { "root_tokens": [ "TRUTH" ], "ending": "0", "form": "?", "partofspeech": "Y", "lemma": "TRUTH", "clitic": "", "root": "TRUTH" } ] }, { "start": 93, "text": "IS", "end": 95, "analysis": [ { "root_tokens": [ "IS" ], "ending": "0", "form": "?", "partofspeech": "Y", "lemma": "IS", "clitic": "", "root": "IS" } ] }, { "start": 96, "text": "OUT", "end": 99, "analysis": [ { "root_tokens": [ "OUT" ], "ending": "0", "form": "?", "partofspeech": "Y", "lemma": "OUT", "clitic": "", "root": "OUT" } ] }, { "start": 100, "text": "SOMEWHERE", "end": 109, "analysis": [ { "root_tokens": [ "Somewhere" ], "ending": "0", "form": "sg n", "partofspeech": "H", "lemma": "Somewhere", "clitic": "", "root": "Somewhere" } ] }, { "start": 110, "text": "!!", "end": 112, "analysis": [ { "root_tokens": [ "!!" ], "ending": "", "form": "", "partofspeech": "Z", "lemma": "!!", "clitic": "", "root": "!!" } ] } ], }

    t["sentences"] = [{'start': t["words"][0]["start"], 'end': t["words"][-1]["end"]}]
    
    Text( t ).verb_chains

**Comment by urdvr** [comment]
Pakun välja lahenduse 3:

Kui "words" kiht eksisteerib, siis kasutada lausestamiseks [sentences_from_tokens](http://www.nltk.org/api/nltk.tokenize.html#nltk.tokenize.punkt.PunktSentenceTokenizer.sentences_from_tokens) meetodit. (juhul kui see on kasutataval tokeniseerijal olemas, (default tokeniseerijal on, kõigil nlkt tokeniseerijatel pole). Vastasel juhul visata veateate.)

**Comment by soras** [comment]
Eeltõstatatud probleemile on [paranduse 'e3619c5'](https://github.com/estnltk/estnltk/commit/e3619c5ab6b21dd5dd03d01ddf1f9a237b744f6c) näol lahendus välja pakutud. Praegu läheb teema sulgemisele.
