### ISSUE TITLE
Join_abbreviation on sõnade tokeniseerimise liiga agressiivne 

### ISSUE THREAD

**Issue by urdvr** [estnltk/estnltk#56]
https://github.com/estnltk/estnltk/blob/devel/estnltk%2Ftokenizers%2Fword_tokenizer.py#L45

Estnltk sõnatokeniseerija lahutab kõigepealt teksti regulaaravaldistega osadeks ja siis vajadusel kombineerib järjestikkused osad kokku. Näiteks kombineeritakse nii murd- ja järgarve.

Kui ma õigesti aru saan, on `join_abbreviation` funktsiooni mõte siduda kokku sõnad nagu "U.S.A".
Hetkel seotakse kokku ka lause lõpp ja algus, kui nende vahel pole tühikut.

``` python
estnltk.Text('Minu nimi on Uku.Mis sinu nimi on?').words
```

> [{'end': 4, 'start': 0, 'text': 'Minu'},
>  {'end': 9, 'start': 5, 'text': 'nimi'},
>  {'end': 12, 'start': 10, 'text': 'on'},
>  {'end': 20, 'start': 13, 'text': 'Uku.Mis'},
>  {'end': 25, 'start': 21, 'text': 'sinu'},
>  {'end': 30, 'start': 26, 'text': 'nimi'},
>  {'end': 33, 'start': 31, 'text': 'on'},
>  {'end': 34, 'start': 33, 'text': '?'}]

``` python
def join_abbreviation(left, middle, right):
    return len(left)>0 and left[-1] in EST_ALPHA and middle == '.' and len(right)>0 and right[0] in EST_ALPHA
```

Lahendus võiks olla pikkuselimiidi seadmine `left` ja `right` muutujatele. Probleemiks muutuksid siis näiteks netikeele tsensuurivältimise sõnakujud (_per.se_, etc). Võimalik on teha ka midagi nutikamat vaadates esinemissagedusi vms. Lahendus peaks igal juhul olema kiire, sest see jookseb iga sõna tokeniseerimisel. Minimaalselt on vajalik võimalikult kiire tagastus juhul kui `middle!='.'`

**Comment by soras** [comment]
Minu senine kogemus ütleb, et kui analüüsida kirjakeelseid/toimetatud tekste, siis tühiku puudumine lause lõpu ja alguse vahel on pigem harv nähtus. Aga seda probleemi võiks, jah, sagedamini kohata, kui analüüsida netikeelt/kommentaariume või muid toimetamata tekste. Kas antud juhul tuli see probleem samuti esile toimetamata tekste analüüsides?

Pole üldse kindel, kuivõrd sageli netikeeles üldse kasutatakse selliseid lühendeid nagu "U.S.A", "e.Kr" või siis isikunime lühendamisi ("M. Unt") -- võimalik, et ei kasutatagi eriti, ning sõnestajale/tokeniseerijale tulekski teha kaks eraldi režiimi: üks toimetamata (ilma lühendireegliteta) ja teine toimetatud tekstide jaoks (koos lühendireeglitega);

**Comment by urdvr** [comment]
> Kas antud juhul tuli see probleem samuti esile toimetamata tekste analüüsides?

Jah. Ja sealjuures on see üsna massiline 

> ning sõnestajale/tokeniseerijale tulekski teha kaks eraldi režiimi: üks toimetamata (ilma lühendireegliteta) ja teine toimetatud tekstide jaoks (koos lühendireeglitega);

See tundub põhjendatud. Peaks mõtlema, kuidas oleks kasutajal kena neid režiime vahetada.

**Comment by soras** [comment]
Uurisin seda probleemi Tasakaalus korpusel ning leidsin, et ka toimetatud tekstides tuleb veidike ette seda lauselõppude ja -alguste kokkuliitmise probleemi (kuigi väga vähe: leidsin circa 600 juhtumit ~15 milj. sõnalise korpuse kohta).

Praegu pakun lahenduseks pikkuse heuristiku: kui mõlemad pooled on vähemalt kahe tähe pikkused, ning parema poole alguses on suurtäht, siis eeldame, et tõenäoliselt on tegu ekslikult kokkuliidetud lauselõpu/algusega:  https://github.com/estnltk/estnltk/commit/2195712ee8b8120640726e5fd52225f810897d4b 
Tasakaalus korpuse 600 juhtumi peal paistab see töötavat, päris toimetamata tekstidel pole katsetanud. Ehk katsetad ise ja annad teada?

Aga lausestamise probleemi see iseenesest ei lahenda: kuna lausestamine toimub enne sõnestamist/tokeniseerimist, siis tuleb kahe lause asemel ikka üks. Võimalik, et lausestaja ümber tuleks ka mingi wrapper tekitada, mis parandab selliseid vigu.

**Comment by soras** [comment]
Versioonis 1.4.1 on sellele probleemile pakutud kaks lahendust: esiteks, sõnatokeniseerijale on lisatud [heuristik, mis püüab tuvastada ekslikult kokkuliidetud lauselõppe/alguseid](https://github.com/estnltk/estnltk/commit/2195712ee8b8120640726e5fd52225f810897d4b), ja teiseks, on lisatud [spetsiifiline lausetokeniseerija](https://github.com/estnltk/estnltk/commit/7a3368a747a80d7dff172e4671d658d917741650), mis (muuhulgas) püüab ekslikult kokkuliidetud sõnade vahelt leida ja parandada lausepiire. Ma arvan, et praegu võib selle teema sulgeda; kui ilmneb uusi toimetamata tekstide tokeniseerimisega seotud probleeme, saab ehk arutelu jätkata uutes teemades.
