### ISSUE TITLE
Silbitamise tugi?

### ISSUE THREAD

**Issue by martinve** [estnltk/estnltk#57]
Kasutan estnltk tööriistu automaatluule genereerimiseks, aga ei õnnestu leida silbitamismoodulit. Kasutan selleks PyPheni: https://github.com/Kozea/Pyphen, mis Eesti keeles annab ~95% täpsuse, aga mõistlik on kasutada töövahendeid mis konkreetselt eesti keele jaoks välja töötatud.

Kui otsida lähtekoodist, siis Vabamorfis on silbitamine C-s realiseeritud ja võimalik on saada teksti foneetiline esitlus. Kas silbitamine puhtal kujul on estnltk paketis (nt, estnltk.Text juures) realiseeritud?

**Comment by urdvr** [comment]
> Kas silbitamine puhtal kujul on estnltk paketis (nt, estnltk.Text juures) realiseeritud?

Võibolla? Keegi uurib seda igal juhul ja kui homseks pole mingit vastust tekkinud, siis ma uurin, et kes täpselt seda uuris ja mis tulemustega.

**Comment by tpetmanson** [comment]
Tere! Estnltk-s on momendil liidestatud ainult morfanalüüs, süntees ja õigekirijakontroll. Silbitamine on implementeerimata. Mõtlesin küll esimese hooga, et foneetilisest märgendusest saab silbid lihtsasti tuletada, sest seal on eritähised väldete ja rõhkude jaoks, aga paraku sellest ei piisa : (

Liidestamise jaoks tundub olevat kõige parem võtta ette vabamorfi Silp klass: https://github.com/Filosoft/vabamorf/blob/f52365944f206d0e614174986bfb1cca001c582b/lib/etana/silp.h . Aga selle kohta maksab ka Tarmolt (@PRR24) uurida, mis kõige lihtsam viis oleks.

**Comment by martinve** [comment]
Tänan vastuse eest. Kuna hetkel on põhitähelepanu keskendunud kujundile ja selle tähendustele - kasutan selleks word2vec-i mis on treenitud eestikeelse Wiki korpusel, siis hetkel jään Pypheni juurde. Mingil hetkel publitseerin oma eksperimendid ka Githubi.

**Comment by tpetmanson** [comment]
Avan selle issue taas, sest plaan on silbitamine tulevikus lisada.

**Comment by tpetmanson** [comment]
Lisan väikese vahemärkuse, et nüüd on devel branchis olemas kood, millega silbitamist saab teha. Aga kuna ma alles just selle lisasin, siis on see väga värke ja võib leida üllatusi.

Lausestamine ja sõnestamine tuleb teha Text klassiga:
```
from estnltk import Text, syllabify_words
from pprint import pprint

words = Text('allmaaraudteejaams toimus võitlus eikellegimaa vanaema kangelase lasteaialastega').word_texts
```
misjärel saab kasutada funktsioone `syllabify_word` või `syllabify_words`. Kui on soov korraga silbitada palju sõnu, siis teine variant on palju kiirem kui kasutada Pythoni for tsüklit iga sõna silbitamiseks. `quantity` on välde ja `accent` on rõhulise silbi tunnus
```
>>> pprint(syllabify_words(words))
[[{'accent': 0, 'quantity': 2, 'syllable': 'all'},
  {'accent': 1, 'quantity': 2, 'syllable': 'maa'},
  {'accent': 0, 'quantity': 2, 'syllable': 'raud'},
  {'accent': 1, 'quantity': 2, 'syllable': 'tee'},
  {'accent': 1, 'quantity': 3, 'syllable': 'jaams'}],
 [{'accent': 1, 'quantity': 2, 'syllable': 'toi'},
  {'accent': 0, 'quantity': 2, 'syllable': 'mus'}],
 [{'accent': 1, 'quantity': 2, 'syllable': 'võit'},
  {'accent': 0, 'quantity': 2, 'syllable': 'lus'}],
 [{'accent': 1, 'quantity': 2, 'syllable': 'ei'},
  {'accent': 0, 'quantity': 2, 'syllable': 'kel'},
  {'accent': 0, 'quantity': 1, 'syllable': 'le'},
  {'accent': 0, 'quantity': 1, 'syllable': 'gi'},
  {'accent': 1, 'quantity': 3, 'syllable': 'maa'}],
 [{'accent': 0, 'quantity': 1, 'syllable': 'va'},
  {'accent': 1, 'quantity': 2, 'syllable': 'nae'},
  {'accent': 0, 'quantity': 1, 'syllable': 'ma'}],
 [{'accent': 1, 'quantity': 2, 'syllable': 'kan'},
  {'accent': 0, 'quantity': 1, 'syllable': 'ge'},
  {'accent': 0, 'quantity': 1, 'syllable': 'la'},
  {'accent': 0, 'quantity': 1, 'syllable': 'se'}],
 [{'accent': 0, 'quantity': 2, 'syllable': 'las'},
  {'accent': 1, 'quantity': 3, 'syllable': 'tea'},
  {'accent': 0, 'quantity': 1, 'syllable': 'i'},
  {'accent': 0, 'quantity': 1, 'syllable': 'a'},
  {'accent': 0, 'quantity': 2, 'syllable': 'las'},
  {'accent': 0, 'quantity': 1, 'syllable': 'te'},
  {'accent': 0, 'quantity': 1, 'syllable': 'ga'}]]
```
Saab ka teistsugusel kujul väljundit küsida:
```
>>> pprint(syllabify_words(words, as_dict=False))
[[('all', 2, 0),
  ('maa', 2, 1),
  ('raud', 2, 0),
  ('tee', 2, 1),
  ('jaams', 3, 1)],
 [('toi', 2, 1), ('mus', 2, 0)],
 [('võit', 2, 1), ('lus', 2, 0)],
 [('ei', 2, 1), ('kel', 2, 0), ('le', 1, 0), ('gi', 1, 0), ('maa', 3, 1)],
 [('va', 1, 0), ('nae', 2, 1), ('ma', 1, 0)],
 [('kan', 2, 1), ('ge', 1, 0), ('la', 1, 0), ('se', 1, 0)],
 [('las', 2, 0),
  ('tea', 3, 1),
  ('i', 1, 0),
  ('a', 1, 0),
  ('las', 2, 0),
  ('te', 1, 0),
  ('ga', 1, 0)]]
```

Nagu näha, siis eksitakse teatud liitsõnadega nagu näiteks `vanaema` ja `lasteaialaps`. Põhjus on selles, et vabamorfi SILP klass on mõeldud lihtsõnade silbitamiseks ja korrektsema väljundi jaoks on vaja silbitajasse integreerida liitsõnapiiride tuvastus.
