### ISSUE TITLE
Dependency parser error

### ISSUE THREAD

**Issue by d009** [estnltk/estnltk#59]
Proovisin koodinäidist (http://estnltk.github.io/estnltk/1.4/tutorials/dependency.html) jooksutada ja ei õnnestunud:
Exception: The number of parsed results <0> does not match the number of words <7>!

**Comment by soras** [comment]
Versioonis [1.4.1](https://github.com/estnltk/estnltk/releases/tag/1.4.1) seda viga enam ei teki.
