### ISSUE TITLE
Estnltk forces install of legacy software

### ISSUE THREAD

**Issue by priidukull** [estnltk/estnltk#60]
The desired behaviour is that estnltk should allow using up to date versions of its dependencies. 

https://github.com/estnltk/estnltk/blob/master/setup.py#L70-L80

**Comment by AleksTk** [comment]
@urdvr , can we use unversioned requirements in setup.py and move versions to requirements.txt?

**Comment by urdvr** [comment]
I think the more appropriate approach would be to specify the minimal versions and keep setup.py and requirements in sync.

Praktikas on meil eeldused kirja pandud kolmes kohas.

- setup.py
- requirements.txt
- conda-recipe/meta.yaml ("travis" branchis, mis on enam-vähem sünkroonis develiga ja kust on ehitatud kõik meie anaconda paketid)

Minu eelistus oleks travis branchi requirements.txt muuta selliseks:
```six>=1.9.0
nltk>=3.0.4
regex>=2015.07.19
pandas>=0.17.1
python-crfsuite>=0.8.
cached-property>=1.2.0
beautifulsoup4>=4.4.0
html5lib
elasticsearch>=2.0.0
```
ja jätta setup.py-sse 
```    
install_requires = [
        'six>=1.9.0',                       # helps to build Py2/Py3 compatible programs
        'nltk>=3.0.4',                      # NLTK mainly used for English
        'regex>=2015.07.19',                # improved Python regular expressions
        'pandas>=0.17.1',                   # Panel Data Analysis library for Python
        'python-crfsuite>=0.8.4',           # Conditional random fields library
        'cached-property>=1.2.0',           # Simple property for caching results
        'beautifulsoup4>=4.4.0',            # HTML parsing library
        'html5lib',              # HTML parsing library
        'elasticsearch>=2.0.0'              # database support
        ],
```
Ning need muudatused enne reliisi develisse tõmmata.
Kommenteeri.

**Comment by urdvr** [comment]
Enam-vähem nii sai tehtud. 1.4.1 peaks lahendama.
