### ISSUE TITLE
Estnltk 1.4 does not install on OS X

### ISSUE THREAD

**Issue by priidukull** [estnltk/estnltk#61]
https://github.com/estnltk/estnltk/tree/osxtest provided a solution for installing estnltk version 1.3 on OS X. That same solution is not sufficient to install estnltk version 1.4 on OS X.

**Comment by andreskytt** [comment]
I concur, 1.4 does not install on OS X. Anaconda no longer recognises the package name, pip install fails because of missing swig-python. After installing that, the install fails because of a failing g++ command spitting out a ton of errors a la 

```
    In file included from estnltk/vabamorf/vabamorf_wrap.cpp:5700:
    In file included from include/etana/vabamorf.h:23:
    In file included from include/etana/etmrf.h:16:
    In file included from include/etana/mrf-mrf.h:16:
    In file included from include/etana/ahel2.h:16:
    In file included from include/etana/post-fsc.h:23:
    In file included from include/fsc/fsc.h:24:
    In file included from include/fsc/fsdata.h:16:
    In file included from include/fsc/fsstream.h:17:
    In file included from include/fsc/fsstring.h:16:
    include/fsc/fsthread.h:321:8: error: unknown type name 'FSTHREADID'
    inline FSTHREADID FSGetCurrentThreadID(){

```

**Comment by andreskytt** [comment]
Confirmed the same messages when building from sources. MacOS Sierra 10.12

**Comment by tpetmanson** [comment]
Tundub, et master branchis ehitamine tõepoolest ebaõnnestub. Põhjus on selles, et 1.4 versiooni pole kaasa saanud OSX-spetsiifiline parandus, mis asub `osxtest` branchis, samas on see olemas `devel` branchis.

Igatahes sain tööle ja installitud sellise workaroundiga:

1. Repo kloonimine

`timosx:~ timo$ git clone git@github.com:estnltk/estnltk.git estnltk`

2. Virtualenv

```
timosx:~ timo$ python3.5 -m virtualenv estnltk_venv
timosx:~ timo$ source ~/estnltk_venv/bin/activate
```

3. Devel branchi kompileerimine

```
(estnltk_venv) timosx:~ timo$ cd estnltk
(estnltk_venv) timosx:estnltk timo$ git checkout devel
(estnltk_venv) timosx:estnltk timo$ python setup.py build
```

... tuleb palju warninguid ja veateateid, aga kompileerub ...

Lihtsalt `setup.py install` käsuga millegipärast mitmete sõltuvuste paigaldamine ebaõnnestub. Samas on sõltuvused olemas ka requirements.txt failis. Osad sõltuvused on seal suhteliselt vanad, aga üpriski ohutu on lihtsalt sealt versiooninumbrid ära kustutada, nii et `requirements.txt` näeb välja selline:

```
six
nltk
regex
pandas
python-crfsuite
cached-property
beautifulsoup4
html5lib
elasticsearch

```
Sõltuvuste uuendamisega on ka see pluss, et neil on olemas tõenäoliselt wheel formaadis binaar, mis lihtsustab protsessi.

`(estnltk_venv) timosx:estnltk timo$ python -m pip install -r requirements.txt`

Versiooninumbrid tuleks ära kustutada ka setup.py failis, pärast mida install õnnestub

`(estnltk_venv) timosx:estnltk timo$ python setup.py install`

Nüüd saab kasutada

```
(estnltk_venv) timosx:~ timo$ python -c "from estnltk import Text; print(Text('Tere estnltk').analysis);"
[[{'root_tokens': ['tere'], 'partofspeech': 'I', 'form': '', 'lemma': 'tere', 'root': 'tere', 'clitic': '', 'ending': '0'}], [{'root_tokens': ['estnltk'], 'partofspeech': 'S', 'form': 'sg n', 'lemma': 'estnltk', 'root': 'estnltk', 'clitic': '', 'ending': '0'}]]
```

Devel branchi kasutamisega muidugi võib kaasneda ka üllatusi, sest seal käib arendus. Üllatuste vältimiseks võib `devel` branchi asemel kasutada ka `osxtest` branchi, mis in sisuliselt 1.3 versioon OSX-spetsiifiliste parandustega.

**Comment by urdvr** [comment]
Ma muretsesin endale nädalaks mäki ja proovin lahendada vähemalt mõningaid mäkiga seotud probleeme.

Esimese asjana laadisin ma estnltk anaconda kanalisse üles osx-64 python 3.5 versiooni devel branchi hetkeseisust.

See peaks olema installitav käsuga

`conda install -c conda-forge -c estnltk estnltk`

Mõned asjad (eelkõige osalausestamine ja selleslt lähtuvad kihid) tõenäoliselt ei tööta. 
Enamik muid asju (morf analüüs ja nimeolemituvastus, kui nimetada mõnda raskemat osa) peaks töötama.

Kas keegi saab seda valideerida?

**Comment by tpetmanson** [comment]
Kui vahepeal on tokeniseerijat uuendatud, siis on ilmselt tarvis NER-i treeningkorpus retokeniseerida ja ka uus mudel treenida. Muude asjade kohta ei oska öelda.

**Comment by andreskytt** [comment]
Proovisin venvi ja devel branchiga. Kompileerimine õnnestub aga install mitte. 

```
crfsuite/lib/crf/src/crf1d_model.c:867:10: error: no matching function for call to 'read_uint32'
    p += read_uint32(p, &ref->num_features);
         ^~~~~~~~~~~

crfsuite/lib/crf/src/crf1d_model.c:141:12: note: candidate function not viable: no known conversion from 'int *' to 'uint32_t *' (aka 'unsigned int *') for 2nd
      argument
static int read_uint32(uint8_t* buffer, uint32_t* value)
           ^
3 warnings and 7 errors generated.
error: Setup script exited with error: command 'g++' failed with exit status 1

```

**Comment by andreskytt** [comment]
Anaconda valideerimisega tegelen

**Comment by andreskytt** [comment]
conda install õnnestus. Kasutamisel  aga

```
Python 3.5.2 |Anaconda 4.2.0 (x86_64)| (default, Jul  2 2016, 17:52:12) 
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from estnltk import Text
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/andreskytt/anaconda3/lib/python3.5/site-packages/estnltk/__init__.py", line 6, in <module>
    from .text import Text
  File "/Users/andreskytt/anaconda3/lib/python3.5/site-packages/estnltk/text.py", line 21, in <module>
    from .tokenizers import EstWordTokenizer
  File "/Users/andreskytt/anaconda3/lib/python3.5/site-packages/estnltk/tokenizers/__init__.py", line 1, in <module>
    from .word_tokenizer import EstWordTokenizer
  File "/Users/andreskytt/anaconda3/lib/python3.5/site-packages/estnltk/tokenizers/word_tokenizer.py", line 18, in <module>
    from nltk.tokenize.regexp import WordPunctTokenizer
  File "/Users/andreskytt/anaconda3/lib/python3.5/site-packages/nltk/__init__.py", line 128, in <module>
    from nltk.chunk import *
  File "/Users/andreskytt/anaconda3/lib/python3.5/site-packages/nltk/chunk/__init__.py", line 157, in <module>
    from nltk.chunk.api import ChunkParserI
  File "/Users/andreskytt/anaconda3/lib/python3.5/site-packages/nltk/chunk/api.py", line 15, in <module>
    from nltk.chunk.util import ChunkScore
  File "/Users/andreskytt/anaconda3/lib/python3.5/site-packages/nltk/chunk/util.py", line 13, in <module>
    from nltk.tag.mapping import map_tag
  File "/Users/andreskytt/anaconda3/lib/python3.5/site-packages/nltk/tag/__init__.py", line 63, in <module>
    from nltk.tag.sequential    import (SequentialBackoffTagger, ContextTagger,
  File "/Users/andreskytt/anaconda3/lib/python3.5/site-packages/nltk/tag/sequential.py", line 25, in <module>
    from nltk.classify import NaiveBayesClassifier
  File "/Users/andreskytt/anaconda3/lib/python3.5/site-packages/nltk/classify/__init__.py", line 98, in <module>
    from nltk.classify.textcat import TextCat
  File "/Users/andreskytt/anaconda3/lib/python3.5/site-packages/nltk/classify/textcat.py", line 47, in <module>
    import regex as re
  File "/Users/andreskytt/anaconda3/lib/python3.5/site-packages/regex.py", line 683, in <module>
    _pattern_type = type(_compile("", 0, {}))
  File "/Users/andreskytt/anaconda3/lib/python3.5/site-packages/regex.py", line 436, in _compile
    pattern_locale = _getlocale()[1]
  File "/Users/andreskytt/anaconda3/lib/python3.5/locale.py", line 577, in getlocale
    return _parse_localename(localename)
  File "/Users/andreskytt/anaconda3/lib/python3.5/locale.py", line 486, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8
>>> 

```

**Comment by urdvr** [comment]
Re:`ValueError: unknown locale: UTF-8`

Tundub, et see on  osx terminalirakenduse ja mitte estnltk ega meie buildi viga.
[See meililist](https://www.mercurial-scm.org/pipermail/mercurial/2007-October/015278.htmll) aastast 2007 paistab kirjeldavat sedasama probleemi.

[See siin on lahenduse kirjeldus conda juhistes](http://conda.pydata.org/docs/troubleshooting.html#unknown-locale)

Kokkuvõtteks: tundub, et me ei saa selle vastu omalt poolt midagi teha, dokumentatsioonis tuleb vea lahendus eraldi välja tuua.

**Comment by urdvr** [comment]
Kokkuvõtteks:

* Hetkel on töötav anaconda osx pakett devel branchist. 
* Eesmärgiks on, et järgmine reliis (ilmselt versiooninumber 1.4.1, loodetavasti enne aasta lõppu) töötab korrektselt mäkil ja ühtlustab anaconda osx/linux/windows versioonid.  

Hetkel panen ma selle issue kinni. Kui peaks ilmnema, et avaldatud anaconda pakett ei tööta või devel branchi kokkuehitamine mäki all ei õnnestu, lahkame neid küsimusi uutes teemades.
