### ISSUE TITLE
Estnltk 1.4 süntaksi analüüs ei tööta python 2.7 keskkonnas

### ISSUE THREAD

**Issue by nostneji** [estnltk/estnltk#62]
Proovisin jooksutada python 2.7 all näidet lehelt http://estnltk.github.io/estnltk/1.4/tutorials/dependency.html ja sain järgmise vea:
`File "C:\bin\Python27\lib\site-packages\estnltk\syntax\tagger.py", line 51, in tag_text
    with tempfile.TemporaryFile(mode='w+', encoding='utf-8') as fp:
TypeError: NamedTemporaryFile() got an unexpected keyword argument 'encoding'
`
Võrreldes dokumentatsiooni lehtedel https://docs.python.org/2.7/library/tempfile.html ja https://docs.python.org/3/library/tempfile.html on näha, et python 2.7 jaoks tõesti puudub argument 'encoding', mistõttu _estnltk\syntax\tagger.py_ vajab mingit alternatiivset lahendust.

**Comment by soras** [comment]
Tänan vearaporti eest.
See on tõesti koht, kus tuleks kasutada ajutiste failide loomisel natuke teistsugust lahendust, nt nagu siin: https://github.com/estnltk/estnltk/blob/devel/estnltk/maltparser_support.py#L166-173

Aga mis puutub estnltk [VISL CG-3 süntaksiliidesesse](http://estnltk.github.io/estnltk/1.4/tutorials/dependency.html), siis sellega võib ette tulla teisigi probleeme. Nt pole praegu Windows-i tuge ning esnltk-ga kaasapandud 'vislcg3' ei pruugi ka Unix-i all tööle hakata ( isiklikult leidsin, et Python3.4-s töölesaamiseks on abi [CG-3'e nullist installeerimisest](https://groups.google.com/forum/#!topic/constraint-grammar/hXsbzyyhIVI) ning kaasapandud ['vislcg3'-e](https://github.com/estnltk/estnltk/blob/devel/estnltk/syntax/tagger.py#L27) asendamisest installitud versiooniga ).

Praegu on estnltk süntaksiliides (VISL CG-3 põhine, tulevikus ka Maltparseri oma) ümbertegemisel. Loodame järgmiseks estnltk versiooniks saavutada töökindlama ja selgema andmeformaadiga liidestuse; rakenduste loomisel tuleks aga ilmselt arvestada seda, et nii süntaksi andmeformaat kui väljakutsumise funktsioonid tõenäoliselt muutuvad tulevikus.

**Comment by soras** [comment]
Versioonis [1.4.1](https://github.com/estnltk/estnltk/releases/tag/1.4.1) on süntaksianalüüsi liides ümber tehtud ning eelpoolmainitud viga seal enam tekkida ei tohiks.
