### ISSUE TITLE
Estnltk1.4: textclassifier not working

### ISSUE THREAD

**Issue by d009** [estnltk/estnltk#65]
http://estnltk.github.io/estnltk/1.4/tutorials/textclassifier.html ei tööta ja teeb estnltk katki :(

**Comment by urdvr** [comment]
Ole hea, täpsusta natuke, mis täpsemalt katki läheb ja kas katki läheb midagi otseselt estnltk teegis või mitte.

Millises keskkonnas? (conda või mitte, osx/linux/windows, pythoni versioon, jne)


Textclassifier on põhimimõtteliselt katki seoses muutustega sklearn teegis. Need on enam-vähem paigatud https://github.com/stacc-ee/textclassifier repos (või vähemasti olid aasta alguse seisuga). Kuna textclassifieril ei ole hetkel vastutavat peremeest, siis on jäänud muutused mergimata ja ma ei tahaks neid ilma suurema testimiseta hakata sisse tõmbama.

**Comment by urdvr** [comment]
On see jätkuvalt probleem?  Lahendab https://github.com/estnltk/textclassifier/commit/c130e4e8ec8a1a1b864d820d5d84610bac6cdac9 asja?

**Comment by d009** [comment]
Jah, nüüd toimib!
