### ISSUE TITLE
Guessing cannot be switched off in morph analysis

### ISSUE THREAD

**Issue by d009** [estnltk/estnltk#66]
```
e = Text("totototo konemilape trpejhk",  guess=False)
e.analysis

```

> [[{'ending': '0', 'root': 'toto_toto', 'partofspeech': 'S', 'clitic': '', 'lemma': 'totototo', 'form': 'sg g', 'root_tokens': ['toto', 'toto']}], [{'ending': '0', 'root': 'konemilape', 'partofspeech': 'S', 'clitic': '', 'lemma': 'konemilape', 'form': 'sg g', 'root_tokens': ['konemilape']}], [{'ending': '0', 'root': 'trpejhk', 'partofspeech': 'S', 'clitic': '', 'lemma': 'trpejhk', 'form': 'sg n', 'root_tokens': ['trpejhk']}]]

**Comment by urdvr** [comment]
Ma kinnitan, et ma näen sama tulemust ja mulle paistab, et `guess` parameeter ei tee midagi. 

Samal ajal jõuab see korrektselt pythonis Vabamorfi instantsini. 
Kõik mis jääb pythonikihist madalamale (s.o. SWIGi kaudu käiv liides vabamorfi C koodiga) on minu jaoks tume ala ja lahendamine võtab aega.

**Comment by tpetmanson** [comment]
Vaatasin, et C++ koodis on selline koht, kus pannakse oletamine peale alati ka siis kui pärisnime analüüsi tehakse. Ilmselt oli sellel ka mingi hea põhjus, aga see et propername=True implitsiitselt ka sätib guess=True on igatahes dokumentatsioonis mainimata.
```
// apply morphoanalysis settings to CLinguistics instance.
void applyMorfSettings(CLinguistic& linguistic, const bool guess, const bool phonetic, const bool propername) {
    linguistic.m_bProperName=propername;
    linguistic.m_bGuess=(guess || linguistic.m_bProperName);   // see rida
    if (linguistic.m_bGuess) {
        linguistic.m_bAbbrevations = false;
    }
    linguistic.m_bPhonetic = phonetic;
}
```
Ma ei saa ise hetkel järele kontrollida, kas see töötab, aga ma prooviks mis väljundi annab

`Text("totototo konemilape trpejhk", guess=False, propername=False).analysis`

**Comment by d009** [comment]
Pärisnimede väljalülitamine annab teistsuguse analüüsitulemuse:
Text("totototo konemilape trpejhk", guess=False, propername=False).analysis
[[{'root_tokens': ['toto', 'toto'], 'lemma': 'totototo', 'root': 'toto_toto', 'form': 'sg n', 'ending': '0', 'partofspeech': 'S', 'clitic': ''}], [{'root_tokens': ['konemilape'], 'lemma': 'konemilape', 'root': 'konemilape', 'form': '', 'ending': '', 'partofspeech': 'Z', 'clitic': ''}], [{'root_tokens': ['trpejhk'], 'lemma': 'trpejhk', 'root': 'trpejhk', 'form': '', 'ending': '', 'partofspeech': 'Z', 'clitic': ''}]]

Ühestamise väljalülitamisest on aga rohkem abi:
Text("totototo konemilape trpejhk", guess=False, disambiguate = False, propername=False).analysis
[[{'root_tokens': ['toto', 'toto'], 'lemma': 'totototo', 'root': 'toto_toto', 'form': 'sg g', 'ending': '0', 'partofspeech': 'S', 'clitic': ''}, {'root_tokens': ['toto', 'toto'], 'lemma': 'totototo', 'root': 'toto_toto', 'form': 'sg n', 'ending': '0', 'partofspeech': 'S', 'clitic': ''}], [], []]

See on ju peaaegu, ka filosoft.ee analüsaator leiab, et "totototo" on piisavalt ilus eestikeelne sõna, et seda oletamiseta analüüsida.

**Comment by urdvr** [comment]
Siis lepime kokku, et 
1. Dage täiendab dokumentatsiooni nii et see vastab tegelikkusele.
2. Mõnes järgmises reliisis kaalume kas me peaksime muutma parameetrite käitumist
Näiteks `guess=False` seaks ka `propername=False` ja kombinatsioon `guess=False, propername=True` annaks vea.
