### ISSUE TITLE
Osalausestaja vajab uuendamist

### ISSUE THREAD

**Issue by urdvr** [estnltk/estnltk#67]
Osalausestaja .jar failid on kokku ehitatud jooksma jre1.7 peal. Viimasel ajal on see probleemiks kujunenud. Windowsi all näiteks osalausetamine ei töötanud, veateade viitas sellele, et jre ja java versioonid ei langenud kokku.

Aadressil https://www.java.com/en/download/faq/java_7.xml on infoks:

> **Where can I get Java 7 downloads?**
> July 2015: Updates for Java 7 are no longer available to the public. Oracle offers updates to Java 7 only for customers who have purchased Java support or have Oracle products that require Java 7.
> 
> **If my Windows system has Java 7, is it updated to Java 7 or Java 8?**
> Coincident with the January 2015 CPU release users with the auto update feature enabled will be migrated from Java 7 to Java 8.

Lahendus oleks ehitada kõik vajalikud jre-d `java-res` uuesti java 8 jdk-ga. Ilmselt on Siim kõige õigem inimene seda tegema.

**Comment by soras** [comment]
Osalausestaja ja ajaväljendite tuvastaja JAR failid said uuendatud.
Ilmselt tekib sarnane probleem ka MaltParseri JAR failide puhul, nii et need tuleks ka millalgi üle vaadata.

**Comment by urdvr** [comment]
Ma katsun seda see nädal testida, olen jälle windowsi taga vahelduseks

**Comment by urdvr** [comment]
Testisin. Probleeme esines kui mul olid nii java1.7 kui 1.8 installitud. 

Kui ma eemaldasin kõik jäljed javast (sealjuures käsitsi /Windows/System32 ja /Windows/SysWOW64 kaustadest) ja installisin puhtalt java 1.8, kõik töötas. 

Loen selle mure hetkel lahendatuks.
