### ISSUE TITLE
"Can't set attribute" when compiling regular expression at estnltk init

### ISSUE THREAD

**Issue by NetBUG** [estnltk/estnltk#70]
Hi! 
After having some troubles compiling estnltk for Mac, I managed to finish installation for Python 3.5.1 (pandas 0.19, numpy 1.11.2).

The module imports flawlessly, but any activity (I tried `word_tokenize()`, `pos_tag()` and `Text(str).lemmas()`) results in the following error, most probably at initialization:
![image](https://cloud.githubusercontent.com/assets/1539823/20095383/22903fb2-a55a-11e6-82c2-e17fb0da6e3c.png)

I did not manage to install estnltk for Python2 indeed on my system.

I cannot do anything about `re` or any other similar module ;(

**Comment by soras** [comment]
Hi!

Can you check what version of [NLTK](http://www.nltk.org/) you are using?
I do remember having a similar error with the older versions of NLTK (3.0.4), but it disappeared when I updated the NLTK to the latest version (3.2.X).

**Comment by NetBUG** [comment]
@soras That helped! Exactly the same versions (3.0.4 -> 3.2.1).
I think this requirement should be somewhere in documentation :)

Suur aitäh!
