### ISSUE TITLE
Estnltk repo size (deleting /dist)

### ISSUE THREAD

**Issue by urdvr** [estnltk/estnltk#71]
We have a history of using the /dist directory to keep and deliver our wheels. The /dist directory is nearing a gigabyte and making the repo hard to manage.

I propose to delete our wheels from the repo, but not try to purge them from our git history. 
I also propose to keep the crfsuite wheels for now as they are smaller, looking for them from our github [releases page](https://github.com/estnltk/estnltk/releases)  is less obvious and they might be of some historical interest and benefit to windows users.

The advantages:
- Our repo size is reduced  
- This communicates clearly that /dist is not a proper place for binary releases

The disadvantages:
- The files are not removed from the repo database and as such this is a half-measure
- - this is somewhat mitigated by the possibility to make shallow clones for development in the future

Agree/disagree/dontcare?

**Comment by AleksTk** [comment]
I would prefer to delete `dist` from git history completely and place contents to the corresponding release and pypi page instead.

**Comment by soras** [comment]
I would also vote for removing `dist`, and also from history (if it is not too much trouble). Though, I am not sure that I understand the disadvantages fully. All estnltk wheels would still be available from https://github.com/estnltk/estnltk/releases , right?

About keeping crfsuite wheels. I think they should be made available from some location (and also correctly linked to from [the installation page](http://estnltk.github.io/estnltk/1.4/tutorials/installation.html#installation-on-windows)). Do we have alternative possibilities for storing these, e.g. at the same web space where wikipedia and koondkorpus dumps are currently stored?

**Comment by AleksTk** [comment]
we can store binaries on ats: http://ats.cs.ut.ee/keeletehnoloogia/estnltk/

**Comment by urdvr** [comment]
The general consensus is that removing /dist from history entirely is the better option.

I experimented with [BFG Repo-Cleaner](https://rtyley.github.io/bfg-repo-cleaner/). I have seen it in action and it has been used successfully at STACC for cleaning crusty repos.

The general process is simple and well documented. 
```bash
#clone repo
git clone --mirror https://github.com/estnltk/estnltk.git

#clean files from HEAD
git clone estnltk.git/ estnltk_working
cd estnltk_working/
rm -rf dist/
git add .
git commit -m "removed dist"
git push
cd ..

#clean history
java -jar ~/bin/bfg.jar --delete-folders dist estnltk.git
cd estnltk.git
git reflog expire --expire=now --all && git gc --prune=now --aggressive
```
This got me to a state where the `estnltk.git` repo contained no /dist directory in the history and `git push` would  push this state to github.


But! Pushing from a dirty repo into `estnltk.git` recreated the  /dist directory with all its contents. This is documented and expected behavior and can't be avoided whatever method we use. 

After the cleaning **everybody** must make clean clones and not push from old ones.
There are some ways to enforce this: 
* change the repo name/url so that pushes from previously cloned local repos would fail
* remove commit access from everyone and return in one-at-a-time when they have sworn to have made clean clones and deleted the old ones.
* something else?

Comments?

**Comment by urdvr** [comment]
I'll freeze this discussion for now to concentrate on release 1.4.1 (which WONT be added to the dist.)

Cleaning up /dist will be handled in the releases coming next year.

**Comment by soras** [comment]
The /dist directory still remains in the history, but this issue is no longer topical. Closing.
