### ISSUE TITLE
Reducing release sizes

### ISSUE THREAD

**Issue by urdvr** [estnltk/estnltk#75]
Estnltk 1.4.1 praegusel kujul on liiga suur, et seda pypisse laadida.

> Submitting dist\estnltk-1.4.1.zip to https://pypi.python.org/pypi
> Upload failed (400): distribution file too large
> error: Upload failed (400): distribution file too large

Ma analüüsisin estnltk-1.4.zip (47M) faili pypist.  

Kuus suuremat faili kompressitud kujul võtavad kokku 38M:

| original | compressed | file                                                           |
|----------|------------|----------------------------------------------------------------|
| 38166972 | 12916383   | estnltk-1.4/estnltk/estner/models/py2_default/model.bin        |
| 21091660 | 7695086    | estnltk-1.4/estnltk/estner/gazetteer/gazetteer.txt             |
| 91685684 | 7289899    | estnltk-1.4/estnltk/wordnet/data/kb69a-utf8.txt                |
| 8941370   | 4198493    | estnltk-1.4/estnltk/vabamorf/dct/et3.dct                       |
| 3230204   | 3221175    | estnltk-1.4/estnltk/java-res/maltparser/estnltkBasedDep.mco    |
| 15950986 | 2973666    | estnltk-1.4/estnltk/corpora/estner.json                        |
                                                                                         |

1.4.1 versionis on neile lisandunud "estnltk-1.4/estnltk/estner/models/py3_default/model.bin ",  ja 
"estnltkBasedDep2.mco" mis lükkavad distributsiooni suuruse üle piiriks oleva 60M.

Mu esimene mõte oli kompressida mõned neist failidest agressiivsemalt kui DEFLATE seda teeb. See ei andnud piisavaid tulemusi.

Milliseid neist failidest võiks kustutada?
Kas meil peaks olema lisaandmete allalaadimise tööriist nagu nltk teegil?
Veel ideid?

**Comment by soras** [comment]
MaltParseri mudelitest on üks üleliigne ja selle võib maha kustutada vastavalt estnltk versioonile:
- 1.4.1 : mudeli "estnltkBasedDep.mco" võib maha kustutada, mudel "estnltkBasedDep2.mco" peab jääma;
- 1.4.2 : mudeli "estnltkBasedDep2.mco" võib maha kustutada, mudel "estnltkECG_f02_b.mco" peab jääma;

Kas "estnltk/corpora/estner.json" on vajalik ainult NER mudelite treenimisel? Sellisel juhul võiks selle äkki eraldi veebilehele tõsta ja paketti panna ainult valmistreenitud mudeli(d)?

**Comment by tpetmanson** [comment]
> Kas meil peaks olema lisaandmete allalaadimise tööriist nagu nltk teegil?
+1

spacy, polyglot, textblob jt on kõigil oma download manager

**Comment by AleksTk** [comment]
@tpetmanson estner.json meil kasutusel ei ole? See on vajalik antud juhul, kui keegi tahab ümbertreenida, mis on suhteliselt ebatõenäoline?

**Comment by tpetmanson** [comment]
@AleksTk Jah, see ainult treenimiseks

**Comment by AleksTk** [comment]
@urdvr ok, siis estner.json võib kustutada.

**Comment by urdvr** [comment]
@AleksTk 
estnltkBasedDep.mco ja estner.json kustutamine 1.4.1 versioonist annab meile ~6MB tagasi.
Kas sellest piisab, et pakk kokku alla 60 MB tuleks? 

Kui jah, siis kustuta need failid ära, märgi versiooniks  __about__.py failis 1.4.1.1 ja lükka need pakk pypisse.

Kui ei, siis jätame praegu 1.4.1 paketi pypisse lükkamata, kirjutame paari nädala jooksul mingi korpuste-ja-mudelte allalaadimisliidese ja katsume veel sel aastal 1.4.2 versiooni välja anda, mis jõuaks ka pypisse.

**Comment by urdvr** [comment]
@AleksTk
Uudiseid?

**Comment by AleksTk** [comment]
Ilma estner.json suurus on 57Mb.
Teen resliisi 1.4.1.1.

**Comment by urdvr** [comment]
Reliis on valmis ja pypis.
Panen selle teema kinni, andmeallalaadija arutelu edasi teemas #77
