### ISSUE TITLE
Estnltk data-downloader planning and development

### ISSUE THREAD

**Issue by urdvr** [estnltk/estnltk#77]
## Eesmärk:

Välja arendada tööriist, mis võimaldab korpusi, andmefaile ja mudeleid jagada estnltk paketist sõltumatult. Motivatsiooni on arutatud #75 juures.

## Lisakasud:

Me saame liidese, mis võimaldaks jagada oluliselt suuremaid andmefaile kui me seda seni oleme teinud. Näiteks võimaldaks see meil jagada @AleksTk word2vec mudeleid.

### Kus andmefaile hoida?

1. cs.ut.ee
2. keeleressursid.ee
3. aws/google cloud, etc

### Kas me peaksime saama andmefaile versioneerida?

Kui jah, siis peab olema lihtne viis kuidas kasutaja saab tuvastada, mis versioonid millistest failidest on tal installitud.

### Kas leidub mõni standardlahendus, mida me saaksime kasutada?

Meil on vaja kohta, kuhu andmed üles laetakse, võimalust kasutajale kuvada nimekirja neist failidest-kataloogidest ning midagi, mis valitud failid alla laeb ja õigesse kohta paneb.

Võiks arvata, et see on juba lahendatud probleem. Ehk saame me kasutada mõnda olemasolevat pythoni moodulit?

### Mis kausta kasutaja andmed laeb?

See peaks olema operatsioonisüsteemipõhine (windowsil AppData/estnltk (mis Win versioonidel AppData on?), linuxil ehk ~/.estnltk, kas osx-il on mingi standardkoht?)

## Ajakava

Data-downloader peaks olema osa 1.4.2 reliisist.

**Comment by soras** [comment]
Alates versioonist 1.7 on andme-allalaadur olemas. Kasutusjuhend on [siin](https://github.com/estnltk/estnltk/blob/main/tutorials/basics/estnltk_resources.ipynb).  See _issue_ läheb kinni.
