### ISSUE TITLE
Layer rewriter is slow on longer texts, branch: devel1_6

### ISSUE THREAD

**Issue by paultammo** [estnltk/estnltk#79]
Mida pikem on tekst, seda kauem kulutab rewriter aega ühe sõna kohta.

    from estnltk.text import words_sentences
    from time import time
    def test(number_of_words):
    
        class DummyRewriter:
            def rewrite(self, record):
                return record
    
        text = words_sentences('tekst '*number_of_words)
        t0 = time()
        layer = text.morf_analysis.layer.rewrite(
                    source_attributes = [],
                    target_attributes = [],
                    rules = DummyRewriter(),
                    name = 'dummy_layer',
                    ambiguous = True
        )
        t1 = time()
    
        print('number of words {:4}, total time: {:.2f} s, time per word: {:.2f} ms'.
              format(number_of_words, t1-t0, 1000*(t1-t0)/number_of_words))
    
    test(10)
    test(100)
    test(1000)
    
    #number of words   10, total time: 0.00 s, time per word: 0.11 ms
    #number of words  100, total time: 0.04 s, time per word: 0.43 ms
    #number of words 1000, total time: 3.46 s, time per word: 3.46 ms

**Comment by urdvr** [comment]
Hetkel peaks lahendama jooksvad probleemid, aga sa võiks testida, kas sinu poolt tundub kõik ok

**Comment by paultammo** [comment]
Läks tuntavalt kiiremaks, aga välja tuli järgmine probleem. 
Mida pikem on tekst, seda kauem kulutab `mark` aega ühe sõna kohta. 

```
from time import time

from estnltk.text import words_sentences
from estnltk.text import Layer


def test(number_of_words):

    text = words_sentences('tekst '*number_of_words)

    dep = Layer(name='new_layer',
            parent='words',
            ambiguous=True,
            attributes=[]
            )
    text._add_layer(dep)
    
    t0 = time()
    for word in text.words:
        word.mark('new_layer')
    t1 = time()

    print('number of words {:4}, total time: {:.2f} s, time per word: {:.2f} ms'.
          format(number_of_words, t1-t0, 1000*(t1-t0)/number_of_words))

test(1)
test(10)
test(100)
test(1000)
test(2000)
```
```
number of words    1, total time: 0.00 s, time per word: 0.04 ms
number of words   10, total time: 0.00 s, time per word: 0.09 ms
number of words  100, total time: 0.06 s, time per word: 0.63 ms
number of words 1000, total time: 5.89 s, time per word: 5.89 ms
number of words 2000, total time: 20.32 s, time per word: 10.16 ms
```

**Comment by urdvr** [comment]
Tasub uuesti proovida

```number of words    1, total time: 0.00 s, time per word: 0.03 ms
number of words   10, total time: 0.00 s, time per word: 0.02 ms
number of words  100, total time: 0.00 s, time per word: 0.04 ms
number of words 1000, total time: 0.11 s, time per word: 0.11 ms
number of words 2000, total time: 0.12 s, time per word: 0.06 ms
```

**Comment by paultammo** [comment]
Korras.
