### ISSUE TITLE
Extra space in abileksikon06utf.lx

### ISSUE THREAD

**Issue by paultammo** [estnltk/estnltk#85]
[Abileksikonis](https://github.com/estnltk/estnltk/blob/master/estnltk/syntax/files/abileksikon06utf.lx) on juure `hiline ` lõpus üleliigne tühik.

**Comment by urdvr** [comment]
Ma arvan, et @kailimp on õige inimene, kellelt nõu küsida kõigi abileksikon06utf.lx küsimustega seoses. (Äkki heljub kuskil ka mõni uuem abileksikonXXutf.lx?) 

Võimalik, et õige koht küsimiseks on https://github.com/EstSyntax/EstCG/issues. Selles repos on ka abileksikon06utf.lx täiesti olemas, ehkki ma pole võrrelnud, kas see erineb meie omast.

**Comment by kailimp** [comment]
Aitäh.
Parandasin EstSyntaxis kõik abileksikoni puudutavad tähelepanekud ära. Abileksikoni praegune tööversioon on 
https://github.com/EstSyntax/EstCG/blob/master/leks.rules mida kutsutakse välja teisest grammatikafailist. Hetkel on sisu paralleelne. Imelik sõnavara abileksikonis on tingitud sellest, et selle esimene versioon kirjutati 20 aastat tagasi ja aluseks oli Saagpaku eesti-inglise sõnaraamat. Muid leksikone rektsiooniinfoga tollal ei olnud.

**Comment by paultammo** [comment]
tänud
