### ISSUE TITLE
Tokenization and morphological analysis of koondkorpus

### ISSUE THREAD

**Issue by paultammo** [estnltk/estnltk#86]
@soras, millist koondkorpust sa kasutasid süntaksi analüüsi juures ja kuidas selle sõnestasid?

Kas morfoloogilise analüüsi parameetrid olid järgmised
> guess: True
> propername: False
> disambiguate: False
> compound: True
> phonetic: False

**Comment by soras** [comment]
_Koondkorpus ja konvertimine_
Kasutasin koondkorpust, mis allalaetav siit: http://ats.cs.ut.ee/keeletehnoloogia/estnltk/koond.zip . Paraku pole see täielik: avastasin, et sealt on täiesti puudu SL Õhtuleht -- vist on jäänud kogemata välja. Igal juhul saab SL Õhtulehe osa ise juurde tekitada, järgides lehel https://estnltk.github.io/estnltk/1.4.1/tutorials/tei.html toodud juhiseid ja kasutades skripti https://github.com/estnltk/estnltk/blob/master/estnltk/examples/convert_koondkorpus.py .

Enne lausestamist/sõnestamist: kasutasin skripti https://github.com/estnltk/estnltk/blob/master/estnltk/examples/split_large_koondkorpus_files.py , et lõigata suured koondkorpuse tekstid väiksemateks juppideks / kirjutada eraldi failidesse, kuna väga suurte failide VISLCG3-st läbilaskmine mul ei õnnestunud. 

_Lausestamine / sõnestamine_
Koondkorpuse failide peal kasutasin EstNLTK vaikelausestajat. Hiljem SL Õhtulehe failidega töötades avastasin, et vaikelausestaja teeb üksjagu vigu ning implementeerisin lausestamise järelparandusteks skripti https://github.com/estnltk/estnltk/blob/master/estnltk/tokenizers/sent_tokenizer_for_koond.py ja kasutasin seda SL Õhtulehe lausestamiseks. Usun, et seda skripti tasub kasutada ka kogu koondkorpuse analüüsil.
Sõnestamisel / sõnadeks jagamisel oli kasutusel EstNLTK vaikesõnestaja.

_Morf analüüs_
Siin kasutasin morf analüüsi koos korpuse/tekstipõhise eel- ja järelühestamisega, ehk siis moodulit https://github.com/estnltk/estnltk/blob/master/estnltk/disambiguator.py   : 

```
from estnltk.disambiguator import Disambiguator
disambiguator = Disambiguator()
disambiguator.disambiguate( [text], disambiguate=True, pre_disambiguate=True, post_disambiguate=True )
```
Sisuliselt peaks see kõhus kasutama parameetreid:
```
guess=True,
disambiguate=True
compound=True
propername=True
phonetic=False
```
@paultammo Aga, jah, kui tekstipõhist eel/järelühestamist kasutada ei soovi, siis Sinu pakutud parameetrid peaksid ka sobima.
