### ISSUE TITLE
name entity recognition custom tagger[help wanted]

### ISSUE THREAD

**Issue by kooolmukul** [estnltk/estnltk#87]
i am training custom models and corpus for my NER .. i want to do one modification that if a word dont have any matching labels in corpus then a label should not added automatically bcz i want to do some operation (like print something OR asing suggestions) when word not matched in corpus...
so what should i change in code..?????

**Comment by AleksTk** [comment]
> if a word dont have any matching labels in corpus then a label should not added automatically

Please elaborate: Are you talking about training or labeling step? What does is it mean "a word dont have any matching labels in corpus"?

**Comment by kooolmukul** [comment]
[https://estnltk.github.io/estnltk/1.4.1/tutorials/ner.html](url)
`from estnltk.ner import NerTagger

document = Text('Eesti koeraspordiliidu ( EKL ) presidendi Piret Laanetu intervjuu Eesti Päevalehele.')

# Load the model and settings
tagger = NerTagger(model_dir)

# ne-tag the document
tagger.tag_document(document)

pprint(list(zip(document.word_texts, document.labels)))`



SO in this, first we Trained our  dataset .. after that at the time of tagging (tagger.tag_document(document)), it tags words by matching them from corpus.. generally if i give a new word which is not in corpus then it tags it with 'O' or some other labels .. so instead of this i want to do that if a new word comes then it should ask a suggestion for that word???

U got my point?

**Comment by AleksTk** [comment]
Ok, got it. Don't see any other way, but to do it manually. Get the training corpus from https://github.com/estnltk/estnltk/tree/version1.3/estnltk/corpora/estner.json, extract the words, and match them against the words in `document.word_texts` or `document.lemmas`.

**Comment by kooolmukul** [comment]
i am using v1.4.1.1, so no estner.json  can we do it by changing source code "estnltk.ner" module( [https://estnltk.github.io/estnltk/1.4.1/api/ner.html](url) )..

**Comment by kooolmukul** [comment]
actually in my project, keywords are from some local language .. so i just made a custom corpus for that with NER labels(category) person(PER), realtion(REL) etc. so i want it make it self learning . so whenever a new word(which is not in custom corpus) comes in input query, then it should ask for suggestion that in which category this word belongs ... 
so for that i was thinking to modify the source code estnltk.ner module given in API documentation [https://estnltk.github.io/estnltk/1.4.1/api/ner.html](url)
but i am confused that what part of module and how i should chage..?

**Comment by AleksTk** [comment]
You can extend `NerTagger` and override method `tag_docuemnts`:
```python
class CustomNerTagger(NerTagger):
    def __init__(self, word_list):
        self.word_list = word_list
        ...

    def tag_documents(self, documents):
        docs = super.tag_documents(documents)
         for d in docs:
              for w in d.words:
                  if w not in self.word_list:
                      do something....
         return docs       

```
